import { UrbanEyeEvent } from '../types/events';

/**
 * URBANEYE — Pune Municipal Corporation (PMC) Damaged Signs Demo Dataset
 * 
 * SCOPE: Pune Municipal Corporation (PMC) jurisdiction only.
 * SIMULATION NOTE: Clearly designated as simulated demo telemetry (source: 'URBANEYE_DEMO_LAYER').
 * Never presented as real civic complaints, live PMPML detections, or official municipal reports.
 * 
 * ROUTE ASSOCIATIONS:
 * Reuses the locked seven Priority Monitoring Corridors (201, 291, 148, 103, 118, 98, 117).
 */
export const PUNE_DAMAGED_SIGN_DEMO_EVENTS: UrbanEyeEvent[] = [
  {
    event_id: 'EVT-PUN-SGN-001',
    event_type: 'DAMAGED_SIGN',
    bus_id: 'MH-12-FC-3312',
    route_id: '148',
    confidence: 0.94,
    severity: 'CRITICAL',
    latitude: 18.5305,
    longitude: 73.8475,
    timestamp: '2026-09-03T08:25:00.000Z',
    evidence_image: '/evidence/damaged_sign.jpg',
    status: 'CORROBORATED',
    source: 'URBANEYE_DEMO_LAYER',
    location_name: 'Sancheti Hospital Chowk, Shivajinagar Junction',
    jurisdiction: 'PMC',
    ward_id: 'W-01-PMC',
    ward_name: 'Shivajinagar',
    corroboration_count: 3,
    corroborating_buses: ['MH-12-FC-3312', 'MH-12-PQ-1204', 'MH-14-GU-8890'],
    priority_score: 94.0,
    hazard_details: {
      hazard_subtype: 'NO ENTRY Regulatory Sign Knocked Down',
      sign_damage_type: 'MISSING',
      lane_affected: 'RIGHT',
    },
    assigned_department: 'PWD',
  },
  {
    event_id: 'EVT-PUN-SGN-002',
    event_type: 'DAMAGED_SIGN',
    bus_id: 'MH-14-BT-9122',
    route_id: '291',
    confidence: 0.92,
    severity: 'CRITICAL',
    latitude: 18.5010,
    longitude: 73.8570,
    timestamp: '2026-09-03T09:15:00.000Z',
    evidence_image: '/evidence/damaged_sign.jpg',
    status: 'CORROBORATED',
    source: 'URBANEYE_DEMO_LAYER',
    location_name: 'Swargate Jedhe Chowk Flyover Split',
    jurisdiction: 'PMC',
    ward_id: 'W-07-PMC',
    ward_name: 'Swargate - Parvati',
    corroboration_count: 2,
    corroborating_buses: ['MH-14-BT-9122', 'MH-12-HB-0911'],
    priority_score: 92.5,
    hazard_details: {
      hazard_subtype: 'Overhead Directional Lane-Split Sign Structural Failure',
      sign_damage_type: 'BENT',
      lane_affected: 'FULL_ROAD',
    },
    assigned_department: 'PWD',
  },
  {
    event_id: 'EVT-PUN-SGN-003',
    event_type: 'DAMAGED_SIGN',
    bus_id: 'MH-12-PQ-1204',
    route_id: '201',
    confidence: 0.90,
    severity: 'HIGH',
    latitude: 18.5580,
    longitude: 73.8795,
    timestamp: '2026-09-03T09:50:00.000Z',
    evidence_image: '/evidence/damaged_sign.jpg',
    status: 'CORROBORATED',
    source: 'URBANEYE_DEMO_LAYER',
    location_name: 'Alandi Road, Vishrantwadi Chowk Junction',
    jurisdiction: 'PMC',
    ward_id: 'W-03-PMC',
    ward_name: 'Yerawada',
    corroboration_count: 2,
    corroborating_buses: ['MH-12-PQ-1204', 'MH-12-RN-4451'],
    priority_score: 77.0,
    hazard_details: {
      hazard_subtype: 'STOP Sign Severely Bent 45 Degrees',
      sign_damage_type: 'BENT',
      lane_affected: 'LEFT',
    },
    assigned_department: 'PWD',
  },
  {
    event_id: 'EVT-PUN-SGN-004',
    event_type: 'DAMAGED_SIGN',
    bus_id: 'MH-12-RN-4451',
    route_id: '118',
    confidence: 0.88,
    severity: 'HIGH',
    latitude: 18.4795,
    longitude: 73.8290,
    timestamp: '2026-09-03T10:30:00.000Z',
    evidence_image: '/evidence/damaged_sign.jpg',
    status: 'DISPATCHED',
    source: 'URBANEYE_DEMO_LAYER',
    location_name: 'Sinhagad Road, Anand Nagar Junction',
    jurisdiction: 'PMC',
    ward_id: 'W-11-PMC',
    ward_name: 'Sinhagad Road',
    corroboration_count: 2,
    corroborating_buses: ['MH-12-RN-4451', 'MH-12-PMP-101'],
    priority_score: 76.5,
    ticket_id: 'TKT-SGN-2026-0812',
    dispatched_at: '2026-09-03T11:00:00.000Z',
    hazard_details: {
      hazard_subtype: 'SPEED LIMIT 40 KM/H Signboard Sheared Off Post',
      sign_damage_type: 'MISSING',
      lane_affected: 'LEFT',
    },
    assigned_department: 'PWD',
  },
  {
    event_id: 'EVT-PUN-SGN-005',
    event_type: 'DAMAGED_SIGN',
    bus_id: 'MH-12-PMP-101',
    route_id: '103',
    confidence: 0.89,
    severity: 'HIGH',
    latitude: 18.5040,
    longitude: 73.8180,
    timestamp: '2026-09-03T11:10:00.000Z',
    evidence_image: '/evidence/damaged_sign.jpg',
    status: 'CORROBORATED',
    source: 'URBANEYE_DEMO_LAYER',
    location_name: 'Paud Road, Ideal Colony Metro Station Median',
    jurisdiction: 'PMC',
    ward_id: 'W-10-PMC',
    ward_name: 'Kothrud - Karve Road',
    corroboration_count: 2,
    corroborating_buses: ['MH-12-PMP-101', 'MH-12-FC-3312'],
    priority_score: 75.0,
    hazard_details: {
      hazard_subtype: 'NO U-TURN Regulatory Sign Twisted Out of View',
      sign_damage_type: 'BENT',
      lane_affected: 'CENTER',
    },
    assigned_department: 'PWD',
  },
  {
    event_id: 'EVT-PUN-SGN-006',
    event_type: 'DAMAGED_SIGN',
    bus_id: 'MH-12-PMP-204',
    route_id: '98',
    confidence: 0.86,
    severity: 'MEDIUM',
    latitude: 18.5145,
    longitude: 73.8420,
    timestamp: '2026-09-03T11:45:00.000Z',
    evidence_image: '/evidence/damaged_sign.jpg',
    status: 'IN_PROGRESS',
    source: 'URBANEYE_DEMO_LAYER',
    location_name: 'Deccan Gymkhana, Fergusson College Road Curve',
    jurisdiction: 'PMC',
    ward_id: 'W-06-PMC',
    ward_name: 'Deccan - Shivaji Nagar',
    corroboration_count: 2,
    corroborating_buses: ['MH-12-PMP-204', 'MH-12-PQ-1204'],
    priority_score: 65.5,
    ticket_id: 'TKT-SGN-2026-0824',
    hazard_details: {
      hazard_subtype: 'PEDESTRIAN CROSSING Sign Heavy Foliage Occlusion',
      sign_damage_type: 'OCCLUDED',
      lane_affected: 'LEFT',
    },
    assigned_department: 'PWD',
  },
  {
    event_id: 'EVT-PUN-SGN-007',
    event_type: 'DAMAGED_SIGN',
    bus_id: 'MH-12-HB-0911',
    route_id: '291',
    confidence: 0.85,
    severity: 'MEDIUM',
    latitude: 18.4590,
    longitude: 73.8560,
    timestamp: '2026-09-03T12:15:00.000Z',
    evidence_image: '/evidence/damaged_sign.jpg',
    status: 'PENDING',
    source: 'URBANEYE_DEMO_LAYER',
    location_name: 'Satara Road, Katraj Dairy Crossroad',
    jurisdiction: 'PMC',
    ward_id: 'W-09-PMC',
    ward_name: 'Katraj',
    corroboration_count: 2,
    corroborating_buses: ['MH-12-HB-0911', 'MH-14-BT-9122'],
    priority_score: 65.0,
    hazard_details: {
      hazard_subtype: 'ONE WAY Directional Arrow Vandalized With Spray Paint',
      sign_damage_type: 'GRAFFITI',
      lane_affected: 'LEFT',
    },
    assigned_department: 'PWD',
  },
  {
    event_id: 'EVT-PUN-SGN-008',
    event_type: 'DAMAGED_SIGN',
    bus_id: 'MH-12-PMP-310',
    route_id: '117',
    confidence: 0.87,
    severity: 'MEDIUM',
    latitude: 18.4510,
    longitude: 73.8120,
    timestamp: '2026-09-03T12:50:00.000Z',
    evidence_image: '/evidence/damaged_sign.jpg',
    status: 'NEW',
    source: 'URBANEYE_DEMO_LAYER',
    location_name: 'Dhayari Main Road Near Benkar Vasti Chowk',
    jurisdiction: 'PMC',
    ward_id: 'W-13-PMC',
    ward_name: 'Dhayari',
    corroboration_count: 1,
    corroborating_buses: ['MH-12-PMP-310'],
    priority_score: 56.0,
    hazard_details: {
      hazard_subtype: 'CAUTION NARROW BRIDGE Sign Plate Face Damaged',
      sign_damage_type: 'BENT',
      lane_affected: 'LEFT',
    },
    assigned_department: 'PWD',
  },
  {
    event_id: 'EVT-PUN-SGN-009',
    event_type: 'DAMAGED_SIGN',
    bus_id: 'MH-12-FC-3312',
    route_id: '201',
    confidence: 0.88,
    severity: 'MEDIUM',
    latitude: 18.5065,
    longitude: 73.9240,
    timestamp: '2026-09-03T13:20:00.000Z',
    evidence_image: '/evidence/damaged_sign.jpg',
    status: 'NEW',
    source: 'URBANEYE_DEMO_LAYER',
    location_name: 'Hadapsar Magarpatta Road, Cybercity East Entrance',
    jurisdiction: 'PMC',
    ward_id: 'W-05-PMC',
    ward_name: 'Hadapsar',
    corroboration_count: 1,
    corroborating_buses: ['MH-12-FC-3312'],
    priority_score: 56.5,
    hazard_details: {
      hazard_subtype: 'BUS STOP Ahead Information Board Bent Backwards',
      sign_damage_type: 'BENT',
      lane_affected: 'LEFT',
    },
    assigned_department: 'PWD',
  },
  {
    event_id: 'EVT-PUN-SGN-010',
    event_type: 'DAMAGED_SIGN',
    bus_id: 'MH-14-GU-8890',
    route_id: '',
    confidence: 0.82,
    severity: 'LOW',
    latitude: 18.5360,
    longitude: 73.8960,
    timestamp: '2026-09-03T14:05:00.000Z',
    evidence_image: '/evidence/damaged_sign.jpg',
    status: 'NEW',
    source: 'URBANEYE_DEMO_LAYER',
    location_name: 'Koregaon Park North Main Road, Lane 4 Crossing',
    jurisdiction: 'PMC',
    ward_id: 'W-08-PMC',
    ward_name: 'Koregaon Park - Ghorpadi',
    corroboration_count: 1,
    corroborating_buses: ['MH-14-GU-8890'],
    priority_score: 44.5,
    hazard_details: {
      hazard_subtype: 'SPEED BREAKER AHEAD Signboard Surface Corrosion',
      sign_damage_type: 'BENT',
      lane_affected: 'LEFT',
    },
    assigned_department: 'PWD',
  },
  {
    event_id: 'EVT-PUN-SGN-011',
    event_type: 'DAMAGED_SIGN',
    bus_id: 'MH-12-RN-4451',
    route_id: '',
    confidence: 0.84,
    severity: 'LOW',
    latitude: 18.5215,
    longitude: 73.8785,
    timestamp: '2026-09-03T14:30:00.000Z',
    evidence_image: '/evidence/damaged_sign.jpg',
    status: 'RESOLVED',
    source: 'URBANEYE_DEMO_LAYER',
    location_name: 'Pune Camp, MG Road Aurora Towers Junction',
    jurisdiction: 'PMC',
    ward_id: 'W-04-PMC',
    ward_name: 'Pune Camp',
    corroboration_count: 1,
    corroborating_buses: ['MH-12-RN-4451'],
    priority_score: 45.0,
    ticket_id: 'TKT-SGN-2026-0790',
    dispatched_at: '2026-09-02T10:00:00.000Z',
    hazard_details: {
      hazard_subtype: 'PARKING RESTRICTION Board Realigned and Fastened',
      sign_damage_type: 'BENT',
      lane_affected: 'LEFT',
    },
    assigned_department: 'PWD',
  },
];
