import { UrbanEyeEvent } from '../types/events';

/**
 * URBANEYE — Pune Municipal Corporation (PMC) Waterlogging Demo Dataset
 * 
 * SCOPE: Pune Municipal Corporation (PMC) jurisdiction only.
 * SIMULATION NOTE: Clearly designated as simulated demo telemetry (source: 'URBANEYE_DEMO_LAYER').
 * Never presented as real civic complaints, live rainfall meters, or official municipal reports.
 * 
 * ROUTE ASSOCIATIONS:
 * Reuses the locked seven Priority Monitoring Corridors (201, 291, 148, 103, 118, 98, 117).
 */
export const PUNE_WATERLOGGING_DEMO_EVENTS: UrbanEyeEvent[] = [
  {
    event_id: 'EVT-PUN-WAT-001',
    event_type: 'WATERLOGGING',
    bus_id: 'MH-12-PQ-1204',
    route_id: '148',
    confidence: 0.96,
    severity: 'CRITICAL',
    latitude: 18.5320,
    longitude: 73.8525,
    timestamp: '2026-09-03T08:15:00.000Z',
    evidence_image: '/evidence/waterlogging.jpg',
    status: 'CORROBORATED',
    source: 'URBANEYE_DEMO_LAYER',
    location_name: 'Shivajinagar Railway Subway Underpass, Route 148 Corridor',
    jurisdiction: 'PMC',
    ward_id: 'W-01-PMC',
    ward_name: 'Shivajinagar',
    corroboration_count: 3,
    corroborating_buses: ['MH-12-PQ-1204', 'MH-12-FC-3312', 'MH-12-PMP-204'],
    priority_score: 95.0,
    hazard_details: {
      hazard_subtype: 'Underpass Stormwater Submergence',
      water_depth_level: 'DEEP_HAZARD',
      lane_affected: 'FULL_ROAD',
    },
    assigned_department: 'DRAINAGE_BOARD',
  },
  {
    event_id: 'EVT-PUN-WAT-002',
    event_type: 'WATERLOGGING',
    bus_id: 'MH-14-BT-9122',
    route_id: '291',
    confidence: 0.94,
    severity: 'CRITICAL',
    latitude: 18.5025,
    longitude: 73.8585,
    timestamp: '2026-09-03T09:10:00.000Z',
    evidence_image: '/evidence/waterlogging.jpg',
    status: 'CORROBORATED',
    source: 'URBANEYE_DEMO_LAYER',
    location_name: 'Swargate Jedhe Chowk Grade Separator Inundation',
    jurisdiction: 'PMC',
    ward_id: 'W-07-PMC',
    ward_name: 'Swargate - Parvati',
    corroboration_count: 3,
    corroborating_buses: ['MH-14-BT-9122', 'MH-12-HB-0911', 'MH-12-PMP-101'],
    priority_score: 93.5,
    hazard_details: {
      hazard_subtype: 'Grade Separator Basin Ponding',
      water_depth_level: 'DEEP_HAZARD',
      lane_affected: 'FULL_ROAD',
    },
    assigned_department: 'DRAINAGE_BOARD',
  },
  {
    event_id: 'EVT-PUN-WAT-003',
    event_type: 'WATERLOGGING',
    bus_id: 'MH-12-FC-3312',
    route_id: '201',
    confidence: 0.91,
    severity: 'HIGH',
    latitude: 18.5030,
    longitude: 73.9305,
    timestamp: '2026-09-03T10:05:00.000Z',
    evidence_image: '/evidence/waterlogging.jpg',
    status: 'CORROBORATED',
    source: 'URBANEYE_DEMO_LAYER',
    location_name: 'Hadapsar Gadital Flyover Drainage Choke, Solapur Road',
    jurisdiction: 'PMC',
    ward_id: 'W-05-PMC',
    ward_name: 'Hadapsar',
    corroboration_count: 2,
    corroborating_buses: ['MH-12-FC-3312', 'MH-12-PQ-1204'],
    priority_score: 82.5,
    hazard_details: {
      hazard_subtype: 'Flyover Runoff Storm Drain Backflow',
      water_depth_level: 'MODERATE',
      lane_affected: 'CENTER',
    },
    assigned_department: 'DRAINAGE_BOARD',
  },
  {
    event_id: 'EVT-PUN-WAT-004',
    event_type: 'WATERLOGGING',
    bus_id: 'MH-14-GU-8890',
    route_id: '201',
    confidence: 0.89,
    severity: 'HIGH',
    latitude: 18.5535,
    longitude: 73.8825,
    timestamp: '2026-09-03T11:15:00.000Z',
    evidence_image: '/evidence/waterlogging.jpg',
    status: 'DISPATCHED',
    source: 'URBANEYE_DEMO_LAYER',
    location_name: 'Yerawada Deccan College Road Subway Dip',
    jurisdiction: 'PMC',
    ward_id: 'W-03-PMC',
    ward_name: 'Yerawada',
    corroboration_count: 2,
    corroborating_buses: ['MH-14-GU-8890', 'MH-12-RN-4451'],
    priority_score: 81.0,
    ticket_id: 'TKT-DRN-2026-0412',
    dispatched_at: '2026-09-03T11:45:00.000Z',
    hazard_details: {
      hazard_subtype: 'Culvert Obstruction Roadway Flooding',
      water_depth_level: 'MODERATE',
      lane_affected: 'RIGHT',
    },
    assigned_department: 'DRAINAGE_BOARD',
  },
  {
    event_id: 'EVT-PUN-WAT-005',
    event_type: 'WATERLOGGING',
    bus_id: 'MH-12-RN-4451',
    route_id: '118',
    confidence: 0.90,
    severity: 'HIGH',
    latitude: 18.4860,
    longitude: 73.8375,
    timestamp: '2026-09-03T09:45:00.000Z',
    evidence_image: '/evidence/waterlogging.jpg',
    status: 'CORROBORATED',
    source: 'URBANEYE_DEMO_LAYER',
    location_name: 'Sinhagad Road, Hingne Khurd Canal Cross-Culvert',
    jurisdiction: 'PMC',
    ward_id: 'W-11-PMC',
    ward_name: 'Sinhagad Road',
    corroboration_count: 2,
    corroborating_buses: ['MH-12-RN-4451', 'MH-12-PMP-101'],
    priority_score: 80.0,
    hazard_details: {
      hazard_subtype: 'Canal Sluice Overflow Stagnation',
      water_depth_level: 'MODERATE',
      lane_affected: 'LEFT',
    },
    assigned_department: 'DRAINAGE_BOARD',
  },
  {
    event_id: 'EVT-PUN-WAT-006',
    event_type: 'WATERLOGGING',
    bus_id: 'MH-12-HB-0911',
    route_id: '291',
    confidence: 0.88,
    severity: 'MEDIUM',
    latitude: 18.4535,
    longitude: 73.8545,
    timestamp: '2026-09-03T10:50:00.000Z',
    evidence_image: '/evidence/waterlogging.jpg',
    status: 'PENDING',
    source: 'URBANEYE_DEMO_LAYER',
    location_name: 'Katraj Lake Outlet Road Near Wonder City Dip',
    jurisdiction: 'PMC',
    ward_id: 'W-09-PMC',
    ward_name: 'Katraj',
    corroboration_count: 2,
    corroborating_buses: ['MH-12-HB-0911', 'MH-12-PMP-101'],
    priority_score: 67.0,
    hazard_details: {
      hazard_subtype: 'Retention Pond Runoff Across Lane',
      water_depth_level: 'MODERATE',
      lane_affected: 'LEFT',
    },
    assigned_department: 'DRAINAGE_BOARD',
  },
  {
    event_id: 'EVT-PUN-WAT-007',
    event_type: 'WATERLOGGING',
    bus_id: 'MH-12-PMP-101',
    route_id: '103',
    confidence: 0.87,
    severity: 'MEDIUM',
    latitude: 18.5085,
    longitude: 73.8345,
    timestamp: '2026-09-03T12:20:00.000Z',
    evidence_image: '/evidence/waterlogging.jpg',
    status: 'IN_PROGRESS',
    source: 'URBANEYE_DEMO_LAYER',
    location_name: 'Karve Road Nal Stop Metro Station Base Drain Dip',
    jurisdiction: 'PMC',
    ward_id: 'W-10-PMC',
    ward_name: 'Kothrud - Karve Road',
    corroboration_count: 2,
    corroborating_buses: ['MH-12-PMP-101', 'MH-12-FC-3312'],
    priority_score: 68.5,
    ticket_id: 'TKT-DRN-2026-0428',
    hazard_details: {
      hazard_subtype: 'Metro Pier Runoff Gutter Spillover',
      water_depth_level: 'MODERATE',
      lane_affected: 'CENTER',
    },
    assigned_department: 'DRAINAGE_BOARD',
  },
  {
    event_id: 'EVT-PUN-WAT-008',
    event_type: 'WATERLOGGING',
    bus_id: 'MH-12-PMP-204',
    route_id: '98',
    confidence: 0.85,
    severity: 'MEDIUM',
    latitude: 18.5180,
    longitude: 73.8395,
    timestamp: '2026-09-03T11:30:00.000Z',
    evidence_image: '/evidence/waterlogging.jpg',
    status: 'NEW',
    source: 'URBANEYE_DEMO_LAYER',
    location_name: 'Deccan Gymkhana Riverside Causeway Road Approach',
    jurisdiction: 'PMC',
    ward_id: 'W-06-PMC',
    ward_name: 'Deccan - Shivaji Nagar',
    corroboration_count: 1,
    corroborating_buses: ['MH-12-PMP-204'],
    priority_score: 55.5,
    hazard_details: {
      hazard_subtype: 'Mutha River Causeway Splash Stagnation',
      water_depth_level: 'MODERATE',
      lane_affected: 'RIGHT',
    },
    assigned_department: 'DRAINAGE_BOARD',
  },
  {
    event_id: 'EVT-PUN-WAT-009',
    event_type: 'WATERLOGGING',
    bus_id: 'MH-12-PMP-310',
    route_id: '117',
    confidence: 0.86,
    severity: 'MEDIUM',
    latitude: 18.4490,
    longitude: 73.8095,
    timestamp: '2026-09-03T13:00:00.000Z',
    evidence_image: '/evidence/waterlogging.jpg',
    status: 'NEW',
    source: 'URBANEYE_DEMO_LAYER',
    location_name: 'Dhayari Phata Canal Bridge Approach Stagnation',
    jurisdiction: 'PMC',
    ward_id: 'W-13-PMC',
    ward_name: 'Dhayari',
    corroboration_count: 1,
    corroborating_buses: ['MH-12-PMP-310'],
    priority_score: 54.0,
    hazard_details: {
      hazard_subtype: 'Storm Drain Choke Water Accumulation',
      water_depth_level: 'MODERATE',
      lane_affected: 'LEFT',
    },
    assigned_department: 'DRAINAGE_BOARD',
  },
  {
    event_id: 'EVT-PUN-WAT-010',
    event_type: 'WATERLOGGING',
    bus_id: 'MH-12-PQ-1204',
    route_id: '201',
    confidence: 0.92,
    severity: 'HIGH',
    latitude: 18.5140,
    longitude: 73.8970,
    timestamp: '2026-09-03T08:50:00.000Z',
    evidence_image: '/evidence/waterlogging.jpg',
    status: 'CORROBORATED',
    source: 'URBANEYE_DEMO_LAYER',
    location_name: 'Pune Camp East Street Low-Lying Dip Near Pulgate',
    jurisdiction: 'PMC',
    ward_id: 'W-04-PMC',
    ward_name: 'Pune Camp',
    corroboration_count: 2,
    corroborating_buses: ['MH-12-PQ-1204', 'MH-12-RN-4451'],
    priority_score: 81.5,
    hazard_details: {
      hazard_subtype: 'Heritage Drain Overflow Water Inundation',
      water_depth_level: 'MODERATE',
      lane_affected: 'CENTER',
    },
    assigned_department: 'DRAINAGE_BOARD',
  },
  {
    event_id: 'EVT-PUN-WAT-011',
    event_type: 'WATERLOGGING',
    bus_id: 'MH-14-GU-8890',
    route_id: '',
    confidence: 0.81,
    severity: 'LOW',
    latitude: 18.5680,
    longitude: 73.9145,
    timestamp: '2026-09-03T12:40:00.000Z',
    evidence_image: '/evidence/waterlogging.jpg',
    status: 'NEW',
    source: 'URBANEYE_DEMO_LAYER',
    location_name: 'Viman Nagar Symbiosis Road Gutter Edge Pooling',
    jurisdiction: 'PMC',
    ward_id: 'W-16-PMC',
    ward_name: 'Viman Nagar',
    corroboration_count: 1,
    corroborating_buses: ['MH-14-GU-8890'],
    priority_score: 35.0,
    hazard_details: {
      hazard_subtype: 'Localized Kerb Drainage Ponding',
      water_depth_level: 'SHALLOW',
      lane_affected: 'LEFT',
    },
    assigned_department: 'DRAINAGE_BOARD',
  },
  {
    event_id: 'EVT-PUN-WAT-012',
    event_type: 'WATERLOGGING',
    bus_id: 'MH-12-FC-3312',
    route_id: '',
    confidence: 0.83,
    severity: 'LOW',
    latitude: 18.4690,
    longitude: 73.8910,
    timestamp: '2026-09-03T13:10:00.000Z',
    evidence_image: '/evidence/waterlogging.jpg',
    status: 'RESOLVED',
    source: 'URBANEYE_DEMO_LAYER',
    location_name: 'Kondhwa Main Road Culvert Approach Shoulder Water',
    jurisdiction: 'PMC',
    ward_id: 'W-14-PMC',
    ward_name: 'Kondhwa Budruk',
    corroboration_count: 1,
    corroborating_buses: ['MH-12-FC-3312'],
    priority_score: 33.0,
    ticket_id: 'TKT-DRN-2026-0395',
    dispatched_at: '2026-09-02T16:00:00.000Z',
    hazard_details: {
      hazard_subtype: 'Desilted Culvert Residual Ponding',
      water_depth_level: 'SHALLOW',
      lane_affected: 'LEFT',
    },
    assigned_department: 'DRAINAGE_BOARD',
  },
];
