import { UrbanEyeEvent } from '../types/events';

/**
 * URBANEYE — Pune Municipal Corporation (PMC) Pothole Demo Dataset
 * 
 * SCOPE: Pune Municipal Corporation (PMC) jurisdiction only.
 * SIMULATION NOTE: Clearly designated as simulated demo telemetry (source: 'URBANEYE_DEMO_LAYER').
 * Never presented as real citizen complaints or unverified real-time municipal records.
 * 
 * ROUTE ASSOCIATIONS:
 * Reuses the locked seven Priority Monitoring Corridors (201, 291, 148, 103, 118, 98, 117).
 */
export const PUNE_POTHOLE_DEMO_EVENTS: UrbanEyeEvent[] = [
  {
    event_id: 'EVT-PUN-POT-001',
    event_type: 'POTHOLE',
    bus_id: 'MH-12-PQ-1204',
    route_id: '201',
    confidence: 0.96,
    severity: 'CRITICAL',
    latitude: 18.5284,
    longitude: 73.8743,
    timestamp: '2026-09-03T09:15:00.000Z',
    evidence_image: '/evidence/pothole.jpg',
    status: 'CORROBORATED',
    source: 'URBANEYE_DEMO_LAYER',
    location_name: 'Pune Railway Station West Approach Road, Route 201 Corridor',
    jurisdiction: 'PMC',
    ward_id: 'W-01-PMC',
    ward_name: 'Shivajinagar - Station',
    corroboration_count: 3,
    corroborating_buses: ['MH-12-PQ-1204', 'MH-12-FC-3312', 'MH-14-GU-8890'],
    priority_score: 94.5,
    estimated_dimensions: { length_cm: 95, width_cm: 70, depth_cm: 16, area_sqm: 0.66 },
    hazard_details: { hazard_subtype: 'Deep Structural Crater', lane_affected: 'CENTER' },
    assigned_department: 'PWD',
  },
  {
    event_id: 'EVT-PUN-POT-002',
    event_type: 'POTHOLE',
    bus_id: 'MH-12-FC-3312',
    route_id: '201',
    confidence: 0.92,
    severity: 'HIGH',
    latitude: 18.5020,
    longitude: 73.9298,
    timestamp: '2026-09-03T10:30:00.000Z',
    evidence_image: '/evidence/pothole.jpg',
    status: 'CORROBORATED',
    source: 'URBANEYE_DEMO_LAYER',
    location_name: 'Hadapsar Gadital Junction, Solapur Road Corridor',
    jurisdiction: 'PMC',
    ward_id: 'W-05-PMC',
    ward_name: 'Hadapsar',
    corroboration_count: 2,
    corroborating_buses: ['MH-12-FC-3312', 'MH-12-PQ-1204'],
    priority_score: 82.0,
    estimated_dimensions: { length_cm: 75, width_cm: 55, depth_cm: 12, area_sqm: 0.41 },
    hazard_details: { hazard_subtype: 'Asphalt Spalling & Edge Depression', lane_affected: 'LEFT' },
    assigned_department: 'PWD',
  },
  {
    event_id: 'EVT-PUN-POT-003',
    event_type: 'POTHOLE',
    bus_id: 'MH-14-GU-8890',
    route_id: '201',
    confidence: 0.89,
    severity: 'MEDIUM',
    latitude: 18.5630,
    longitude: 73.8790,
    timestamp: '2026-09-03T11:45:00.000Z',
    evidence_image: '/evidence/pothole.jpg',
    status: 'NEW',
    source: 'URBANEYE_DEMO_LAYER',
    location_name: 'Vishrantwadi Junction, Alandi Road Approach',
    jurisdiction: 'PMC',
    ward_id: 'W-03-PMC',
    ward_name: 'Yerawada - Vishrantwadi',
    corroboration_count: 1,
    corroborating_buses: ['MH-14-GU-8890'],
    priority_score: 58.5,
    estimated_dimensions: { length_cm: 45, width_cm: 35, depth_cm: 7, area_sqm: 0.16 },
    hazard_details: { hazard_subtype: 'Mid-Lane Surface Raveling', lane_affected: 'CENTER' },
    assigned_department: 'PWD',
  },
  {
    event_id: 'EVT-PUN-POT-004',
    event_type: 'POTHOLE',
    bus_id: 'MH-12-RN-4451',
    route_id: '201',
    confidence: 0.94,
    severity: 'HIGH',
    latitude: 18.5130,
    longitude: 73.8965,
    timestamp: '2026-09-03T12:10:00.000Z',
    evidence_image: '/evidence/pothole.jpg',
    status: 'DISPATCHED',
    source: 'URBANEYE_DEMO_LAYER',
    location_name: 'Pune Camp, Near Pulgate Bus Station',
    jurisdiction: 'PMC',
    ward_id: 'W-04-PMC',
    ward_name: 'Pune Camp',
    corroboration_count: 2,
    corroborating_buses: ['MH-12-RN-4451', 'MH-14-BT-9122'],
    priority_score: 79.5,
    ticket_id: 'TKT-PWD-2026-1041',
    dispatched_at: '2026-09-03T12:45:00.000Z',
    estimated_dimensions: { length_cm: 65, width_cm: 50, depth_cm: 11, area_sqm: 0.32 },
    hazard_details: { hazard_subtype: 'Traffic Lane Edge Failure', lane_affected: 'RIGHT' },
    assigned_department: 'PWD',
  },
  {
    event_id: 'EVT-PUN-POT-005',
    event_type: 'POTHOLE',
    bus_id: 'MH-14-BT-9122',
    route_id: '291',
    confidence: 0.95,
    severity: 'CRITICAL',
    latitude: 18.5018,
    longitude: 73.8580,
    timestamp: '2026-09-03T08:20:00.000Z',
    evidence_image: '/evidence/pothole.jpg',
    status: 'CORROBORATED',
    source: 'URBANEYE_DEMO_LAYER',
    location_name: 'Swargate Bus Terminal North Entry, Jedhe Chowk',
    jurisdiction: 'PMC',
    ward_id: 'W-07-PMC',
    ward_name: 'Swargate - Parvati',
    corroboration_count: 3,
    corroborating_buses: ['MH-14-BT-9122', 'MH-12-HB-0911', 'MH-12-PMP-101'],
    priority_score: 96.0,
    estimated_dimensions: { length_cm: 110, width_cm: 80, depth_cm: 18, area_sqm: 0.88 },
    hazard_details: { hazard_subtype: 'Heavy Transit Axle Impact Cavity', lane_affected: 'FULL_ROAD' },
    assigned_department: 'PWD',
  },
  {
    event_id: 'EVT-PUN-POT-006',
    event_type: 'POTHOLE',
    bus_id: 'MH-12-HB-0911',
    route_id: '291',
    confidence: 0.91,
    severity: 'HIGH',
    latitude: 18.4700,
    longitude: 73.8640,
    timestamp: '2026-09-03T09:40:00.000Z',
    evidence_image: '/evidence/pothole.jpg',
    status: 'CORROBORATED',
    source: 'URBANEYE_DEMO_LAYER',
    location_name: 'Bibwewadi Market Yard Outer Gate Corridor',
    jurisdiction: 'PMC',
    ward_id: 'W-08-PMC',
    ward_name: 'Bibwewadi',
    corroboration_count: 2,
    corroborating_buses: ['MH-12-HB-0911', 'MH-14-BT-9122'],
    priority_score: 81.0,
    estimated_dimensions: { length_cm: 70, width_cm: 45, depth_cm: 10, area_sqm: 0.31 },
    hazard_details: { hazard_subtype: 'Freight Transit Lane Pothole', lane_affected: 'LEFT' },
    assigned_department: 'PWD',
  },
  {
    event_id: 'EVT-PUN-POT-007',
    event_type: 'POTHOLE',
    bus_id: 'MH-12-PMP-101',
    route_id: '291',
    confidence: 0.87,
    severity: 'MEDIUM',
    latitude: 18.4529,
    longitude: 73.8550,
    timestamp: '2026-09-03T10:15:00.000Z',
    evidence_image: '/evidence/pothole.jpg',
    status: 'PENDING',
    source: 'URBANEYE_DEMO_LAYER',
    location_name: 'Katraj Bus Terminus Roundabout, Satara Road',
    jurisdiction: 'PMC',
    ward_id: 'W-09-PMC',
    ward_name: 'Katraj',
    corroboration_count: 1,
    corroborating_buses: ['MH-12-PMP-101'],
    priority_score: 56.0,
    estimated_dimensions: { length_cm: 40, width_cm: 40, depth_cm: 6, area_sqm: 0.16 },
    hazard_details: { hazard_subtype: 'Bus Bay Approach Depression', lane_affected: 'CENTER' },
    assigned_department: 'PWD',
  },
  {
    event_id: 'EVT-PUN-POT-008',
    event_type: 'POTHOLE',
    bus_id: 'MH-12-PQ-1204',
    route_id: '148',
    confidence: 0.93,
    severity: 'HIGH',
    latitude: 18.5314,
    longitude: 73.8520,
    timestamp: '2026-09-03T07:50:00.000Z',
    evidence_image: '/evidence/pothole.jpg',
    status: 'CORROBORATED',
    source: 'URBANEYE_DEMO_LAYER',
    location_name: 'Shivajinagar Station Underpass Corridor',
    jurisdiction: 'PMC',
    ward_id: 'W-01-PMC',
    ward_name: 'Shivajinagar',
    corroboration_count: 2,
    corroborating_buses: ['MH-12-PQ-1204', 'MH-12-PMP-204'],
    priority_score: 83.5,
    estimated_dimensions: { length_cm: 80, width_cm: 60, depth_cm: 13, area_sqm: 0.48 },
    hazard_details: { hazard_subtype: 'Subway Drainage Joint Ravelling', lane_affected: 'RIGHT' },
    assigned_department: 'PWD',
  },
  {
    event_id: 'EVT-PUN-POT-009',
    event_type: 'POTHOLE',
    bus_id: 'MH-12-PMP-204',
    route_id: '148',
    confidence: 0.82,
    severity: 'LOW',
    latitude: 18.5600,
    longitude: 73.8340,
    timestamp: '2026-09-03T13:05:00.000Z',
    evidence_image: '/evidence/pothole.jpg',
    status: 'NEW',
    source: 'URBANEYE_DEMO_LAYER',
    location_name: 'Aundh Bremen Chowk Approach Road',
    jurisdiction: 'PMC',
    ward_id: 'W-02-PMC',
    ward_name: 'Aundh',
    corroboration_count: 1,
    corroborating_buses: ['MH-12-PMP-204'],
    priority_score: 38.0,
    estimated_dimensions: { length_cm: 30, width_cm: 25, depth_cm: 4, area_sqm: 0.08 },
    hazard_details: { hazard_subtype: 'Surface Layer Flaking', lane_affected: 'LEFT' },
    assigned_department: 'PWD',
  },
  {
    event_id: 'EVT-PUN-POT-010',
    event_type: 'POTHOLE',
    bus_id: 'MH-12-FC-3312',
    route_id: '103',
    confidence: 0.94,
    severity: 'CRITICAL',
    latitude: 18.5080,
    longitude: 73.8350,
    timestamp: '2026-09-03T09:05:00.000Z',
    evidence_image: '/evidence/pothole.jpg',
    status: 'CORROBORATED',
    source: 'URBANEYE_DEMO_LAYER',
    location_name: 'Karve Road, Nal Stop Flyover Pillar 14',
    jurisdiction: 'PMC',
    ward_id: 'W-10-PMC',
    ward_name: 'Kothrud - Karve Road',
    corroboration_count: 3,
    corroborating_buses: ['MH-12-FC-3312', 'MH-14-GU-8890', 'MH-12-PMP-310'],
    priority_score: 93.0,
    estimated_dimensions: { length_cm: 90, width_cm: 65, depth_cm: 15, area_sqm: 0.58 },
    hazard_details: { hazard_subtype: 'Metro Pillar Base Road Collapse', lane_affected: 'CENTER' },
    assigned_department: 'PWD',
  },
  {
    event_id: 'EVT-PUN-POT-011',
    event_type: 'POTHOLE',
    bus_id: 'MH-14-GU-8890',
    route_id: '103',
    confidence: 0.88,
    severity: 'MEDIUM',
    latitude: 18.5030,
    longitude: 73.8050,
    timestamp: '2026-09-03T11:20:00.000Z',
    evidence_image: '/evidence/pothole.jpg',
    status: 'IN_PROGRESS',
    source: 'URBANEYE_DEMO_LAYER',
    location_name: 'Kothrud Bus Depot Entrance, Paud Road',
    jurisdiction: 'PMC',
    ward_id: 'W-10-PMC',
    ward_name: 'Kothrud',
    corroboration_count: 2,
    corroborating_buses: ['MH-14-GU-8890', 'MH-12-FC-3312'],
    priority_score: 66.5,
    ticket_id: 'TKT-PWD-2026-1077',
    estimated_dimensions: { length_cm: 50, width_cm: 40, depth_cm: 8, area_sqm: 0.20 },
    hazard_details: { hazard_subtype: 'Heavy Turn Wheel Rutting', lane_affected: 'LEFT' },
    assigned_department: 'PWD',
  },
  {
    event_id: 'EVT-PUN-POT-012',
    event_type: 'POTHOLE',
    bus_id: 'MH-12-RN-4451',
    route_id: '118',
    confidence: 0.90,
    severity: 'HIGH',
    latitude: 18.4850,
    longitude: 73.8380,
    timestamp: '2026-09-03T08:45:00.000Z',
    evidence_image: '/evidence/pothole.jpg',
    status: 'CORROBORATED',
    source: 'URBANEYE_DEMO_LAYER',
    location_name: 'Sinhagad Road, Hingne Khurd Junction',
    jurisdiction: 'PMC',
    ward_id: 'W-11-PMC',
    ward_name: 'Sinhagad Road',
    corroboration_count: 2,
    corroborating_buses: ['MH-12-RN-4451', 'MH-12-PMP-101'],
    priority_score: 80.5,
    estimated_dimensions: { length_cm: 75, width_cm: 50, depth_cm: 11, area_sqm: 0.38 },
    hazard_details: { hazard_subtype: 'Deep Trench Settlement', lane_affected: 'CENTER' },
    assigned_department: 'PWD',
  },
  {
    event_id: 'EVT-PUN-POT-013',
    event_type: 'POTHOLE',
    bus_id: 'MH-14-BT-9122',
    route_id: '118',
    confidence: 0.85,
    severity: 'MEDIUM',
    latitude: 18.4650,
    longitude: 73.8250,
    timestamp: '2026-09-03T10:50:00.000Z',
    evidence_image: '/evidence/pothole.jpg',
    status: 'NEW',
    source: 'URBANEYE_DEMO_LAYER',
    location_name: 'Vadgaon Budruk Phata, Sinhagad Road',
    jurisdiction: 'PMC',
    ward_id: 'W-11-PMC',
    ward_name: 'Vadgaon Budruk',
    corroboration_count: 1,
    corroborating_buses: ['MH-14-BT-9122'],
    priority_score: 55.0,
    estimated_dimensions: { length_cm: 45, width_cm: 30, depth_cm: 6, area_sqm: 0.14 },
    hazard_details: { hazard_subtype: 'Shoulder Ravelling Pothole', lane_affected: 'LEFT' },
    assigned_department: 'PWD',
  },
  {
    event_id: 'EVT-PUN-POT-014',
    event_type: 'POTHOLE',
    bus_id: 'MH-12-HB-0911',
    route_id: '98',
    confidence: 0.88,
    severity: 'HIGH',
    latitude: 18.5170,
    longitude: 73.8400,
    timestamp: '2026-09-03T07:15:00.000Z',
    evidence_image: '/evidence/pothole.jpg',
    status: 'DISPATCHED',
    source: 'URBANEYE_DEMO_LAYER',
    location_name: 'Deccan Gymkhana Bus Stop, Karve Road Entry',
    jurisdiction: 'PMC',
    ward_id: 'W-06-PMC',
    ward_name: 'Deccan - Shivaji Nagar',
    corroboration_count: 2,
    corroborating_buses: ['MH-12-HB-0911', 'MH-12-PQ-1204'],
    priority_score: 81.5,
    ticket_id: 'TKT-PWD-2026-1092',
    dispatched_at: '2026-09-03T08:00:00.000Z',
    estimated_dimensions: { length_cm: 70, width_cm: 55, depth_cm: 12, area_sqm: 0.38 },
    hazard_details: { hazard_subtype: 'Transit Stop Deceleration Depression', lane_affected: 'LEFT' },
    assigned_department: 'PWD',
  },
  {
    event_id: 'EVT-PUN-POT-015',
    event_type: 'POTHOLE',
    bus_id: 'MH-12-PMP-101',
    route_id: '98',
    confidence: 0.81,
    severity: 'LOW',
    latitude: 18.4800,
    longitude: 73.7920,
    timestamp: '2026-09-03T12:35:00.000Z',
    evidence_image: '/evidence/pothole.jpg',
    status: 'NEW',
    source: 'URBANEYE_DEMO_LAYER',
    location_name: 'Ganpati Matha, Warje Malwadi NDA Road',
    jurisdiction: 'PMC',
    ward_id: 'W-12-PMC',
    ward_name: 'Warje',
    corroboration_count: 1,
    corroborating_buses: ['MH-12-PMP-101'],
    priority_score: 36.5,
    estimated_dimensions: { length_cm: 30, width_cm: 20, depth_cm: 4, area_sqm: 0.06 },
    hazard_details: { hazard_subtype: 'Surface Wear Depression', lane_affected: 'RIGHT' },
    assigned_department: 'PWD',
  },
  {
    event_id: 'EVT-PUN-POT-016',
    event_type: 'POTHOLE',
    bus_id: 'MH-12-PMP-204',
    route_id: '117',
    confidence: 0.89,
    severity: 'HIGH',
    latitude: 18.4480,
    longitude: 73.8090,
    timestamp: '2026-09-03T09:55:00.000Z',
    evidence_image: '/evidence/pothole.jpg',
    status: 'CORROBORATED',
    source: 'URBANEYE_DEMO_LAYER',
    location_name: 'Dhayari Phata Main Junction, Sinhagad Corridor',
    jurisdiction: 'PMC',
    ward_id: 'W-13-PMC',
    ward_name: 'Dhayari',
    corroboration_count: 2,
    corroborating_buses: ['MH-12-PMP-204', 'MH-14-BT-9122'],
    priority_score: 77.0,
    estimated_dimensions: { length_cm: 65, width_cm: 48, depth_cm: 10, area_sqm: 0.31 },
    hazard_details: { hazard_subtype: 'Road Expansion Seam Failure', lane_affected: 'CENTER' },
    assigned_department: 'PWD',
  },
  {
    event_id: 'EVT-PUN-POT-017',
    event_type: 'POTHOLE',
    bus_id: 'MH-12-PMP-310',
    route_id: '117',
    confidence: 0.84,
    severity: 'MEDIUM',
    latitude: 18.4920,
    longitude: 73.8420,
    timestamp: '2026-09-03T11:05:00.000Z',
    evidence_image: '/evidence/pothole.jpg',
    status: 'NEW',
    source: 'URBANEYE_DEMO_LAYER',
    location_name: 'Parvati Water Works Approach, Sinhagad Road',
    jurisdiction: 'PMC',
    ward_id: 'W-07-PMC',
    ward_name: 'Parvati',
    corroboration_count: 1,
    corroborating_buses: ['MH-12-PMP-310'],
    priority_score: 54.0,
    estimated_dimensions: { length_cm: 42, width_cm: 32, depth_cm: 6, area_sqm: 0.13 },
    hazard_details: { hazard_subtype: 'Manhole Collar Subsidence', lane_affected: 'LEFT' },
    assigned_department: 'PWD',
  },
  {
    event_id: 'EVT-PUN-POT-018',
    event_type: 'POTHOLE',
    bus_id: 'MH-12-FC-3312',
    route_id: '',
    confidence: 0.91,
    severity: 'HIGH',
    latitude: 18.4682,
    longitude: 73.8905,
    timestamp: '2026-09-03T08:35:00.000Z',
    evidence_image: '/evidence/pothole.jpg',
    status: 'PENDING',
    source: 'URBANEYE_DEMO_LAYER',
    location_name: 'Kondhwa Khadi Machine Chowk Main Road',
    jurisdiction: 'PMC',
    ward_id: 'W-14-PMC',
    ward_name: 'Kondhwa Budruk',
    corroboration_count: 1,
    corroborating_buses: ['MH-12-FC-3312'],
    priority_score: 73.5,
    estimated_dimensions: { length_cm: 72, width_cm: 52, depth_cm: 11, area_sqm: 0.37 },
    hazard_details: { hazard_subtype: 'Stone Quarry Tipper Rutting Pothole', lane_affected: 'CENTER' },
    assigned_department: 'PWD',
  },
  {
    event_id: 'EVT-PUN-POT-019',
    event_type: 'POTHOLE',
    bus_id: 'MH-12-PQ-1204',
    route_id: '',
    confidence: 0.86,
    severity: 'MEDIUM',
    latitude: 18.5360,
    longitude: 73.8940,
    timestamp: '2026-09-03T10:40:00.000Z',
    evidence_image: '/evidence/pothole.jpg',
    status: 'RESOLVED',
    source: 'URBANEYE_DEMO_LAYER',
    location_name: 'Koregaon Park North Main Road, Near Lane 5',
    jurisdiction: 'PMC',
    ward_id: 'W-15-PMC',
    ward_name: 'Koregaon Park',
    corroboration_count: 2,
    corroborating_buses: ['MH-12-PQ-1204', 'MH-14-GU-8890'],
    priority_score: 65.0,
    ticket_id: 'TKT-PWD-2026-0988',
    dispatched_at: '2026-09-02T14:00:00.000Z',
    estimated_dimensions: { length_cm: 45, width_cm: 38, depth_cm: 7, area_sqm: 0.17 },
    hazard_details: { hazard_subtype: 'Patched Bitumen Re-raveling', lane_affected: 'LEFT' },
    assigned_department: 'PWD',
  },
  {
    event_id: 'EVT-PUN-POT-020',
    event_type: 'POTHOLE',
    bus_id: 'MH-14-GU-8890',
    route_id: '',
    confidence: 0.83,
    severity: 'LOW',
    latitude: 18.5670,
    longitude: 73.9140,
    timestamp: '2026-09-03T13:20:00.000Z',
    evidence_image: '/evidence/pothole.jpg',
    status: 'NEW',
    source: 'URBANEYE_DEMO_LAYER',
    location_name: 'Viman Nagar Central Avenue, Near Phoenix Corridor',
    jurisdiction: 'PMC',
    ward_id: 'W-16-PMC',
    ward_name: 'Viman Nagar',
    corroboration_count: 1,
    corroborating_buses: ['MH-14-GU-8890'],
    priority_score: 34.5,
    estimated_dimensions: { length_cm: 28, width_cm: 22, depth_cm: 3, area_sqm: 0.06 },
    hazard_details: { hazard_subtype: 'Early Surface Abrasion', lane_affected: 'RIGHT' },
    assigned_department: 'PWD',
  },
  {
    event_id: 'EVT-PUN-POT-021',
    event_type: 'POTHOLE',
    bus_id: 'MH-12-RN-4451',
    route_id: '201',
    confidence: 0.90,
    severity: 'MEDIUM',
    latitude: 18.5525,
    longitude: 73.8820,
    timestamp: '2026-09-03T09:30:00.000Z',
    evidence_image: '/evidence/pothole.jpg',
    status: 'PENDING',
    source: 'URBANEYE_DEMO_LAYER',
    location_name: 'Yerawada Gunjan Chowk, Airport Road Corridor',
    jurisdiction: 'PMC',
    ward_id: 'W-03-PMC',
    ward_name: 'Yerawada',
    corroboration_count: 2,
    corroborating_buses: ['MH-12-RN-4451', 'MH-14-BT-9122'],
    priority_score: 68.0,
    estimated_dimensions: { length_cm: 55, width_cm: 40, depth_cm: 8, area_sqm: 0.22 },
    hazard_details: { hazard_subtype: 'Junction Braking Ripple Pothole', lane_affected: 'CENTER' },
    assigned_department: 'PWD',
  },
];
