/**
 * URBANEYE — Teammate YOLO Traffic Analysis Stream Telemetry
 * 
 * Extracted directly from continuous inference video: traffic_density_output (1).mp4
 * Model: YOLOv8 vehicle detection (car, motorcycle, bus, truck)
 * Bounding boxes & counts generated frame-by-frame.
 * Total frames: 551 | FPS: 29.97 | Resolution: 720x1280
 */

export interface YoloTrafficFrame {
  frame_index: number;
  timestamp_sec: number;
  total_vehicles: number;
  cars: number;
  bikes: number;
  buses: number;
  trucks: number;
  density_score: number; // vehicles / 20 capacity ROI
  traffic_state: 'LOW' | 'MEDIUM' | 'HEAVY';
  severity: 'LOW' | 'MEDIUM' | 'HIGH';
  confidence: number;
}

export interface YoloTrafficStreamMeta {
  model_name: string;
  stream_id: string;
  stream_title: string;
  source: string;
  video_url: string;
  total_frames: number;
  fps: number;
  duration_seconds: number;
  classes: string[];
  tracking_present: boolean;
  speed_available: boolean;
  location: string;
  density_formula: string;
  congestion_formula: string;
}

export const YOLO_TRAFFIC_STREAM_META: YoloTrafficStreamMeta = {
  model_name: 'YOLOv8 — Vehicle Detection & Density Estimator',
  stream_id: 'CAM-EDGE-01',
  stream_title: 'Live Camera Traffic Analysis',
  source: 'URBANEYE_CAMERA_LIVE',
  video_url: '/traffic_density_output.mp4',
  total_frames: 551,
  fps: 29.97,
  duration_seconds: 18.38,
  classes: ['car', 'motorcycle', 'bus', 'truck'],
  tracking_present: false, // Truthful: No ByteTrack/BoT-SORT IDs on bounding boxes
  speed_available: false,  // Truthful: Single-camera view without ground-plane calibration
  location: 'Camera Traffic Analysis — Location Unspecified',
  density_formula: 'Camera Density = (Detected Vehicles / 20 ROI Capacity) * 100%',
  congestion_formula: 'LOW: <=8 vehicles | MEDIUM: 9-15 vehicles | HEAVY: >15 vehicles',
};

export const YOLO_TRAFFIC_TELEMETRY_FRAMES: YoloTrafficFrame[] = [
  {
    "frame_index": 0,
    "timestamp_sec": 0.0,
    "total_vehicles": 6,
    "cars": 2,
    "bikes": 2,
    "buses": 0,
    "trucks": 2,
    "density_score": 30.0,
    "traffic_state": "LOW",
    "severity": "LOW",
    "confidence": 0.91
  },
  {
    "frame_index": 3,
    "timestamp_sec": 0.1,
    "total_vehicles": 10,
    "cars": 6,
    "bikes": 2,
    "buses": 0,
    "trucks": 2,
    "density_score": 50.0,
    "traffic_state": "MEDIUM",
    "severity": "MEDIUM",
    "confidence": 0.91
  },
  {
    "frame_index": 6,
    "timestamp_sec": 0.2,
    "total_vehicles": 8,
    "cars": 5,
    "bikes": 1,
    "buses": 1,
    "trucks": 1,
    "density_score": 40.0,
    "traffic_state": "LOW",
    "severity": "LOW",
    "confidence": 0.91
  },
  {
    "frame_index": 9,
    "timestamp_sec": 0.3,
    "total_vehicles": 7,
    "cars": 5,
    "bikes": 1,
    "buses": 0,
    "trucks": 1,
    "density_score": 35.0,
    "traffic_state": "LOW",
    "severity": "LOW",
    "confidence": 0.91
  },
  {
    "frame_index": 12,
    "timestamp_sec": 0.4,
    "total_vehicles": 4,
    "cars": 2,
    "bikes": 1,
    "buses": 1,
    "trucks": 0,
    "density_score": 20.0,
    "traffic_state": "LOW",
    "severity": "LOW",
    "confidence": 0.91
  },
  {
    "frame_index": 15,
    "timestamp_sec": 0.5,
    "total_vehicles": 5,
    "cars": 3,
    "bikes": 1,
    "buses": 1,
    "trucks": 0,
    "density_score": 25.0,
    "traffic_state": "LOW",
    "severity": "LOW",
    "confidence": 0.91
  },
  {
    "frame_index": 18,
    "timestamp_sec": 0.6,
    "total_vehicles": 7,
    "cars": 3,
    "bikes": 3,
    "buses": 1,
    "trucks": 0,
    "density_score": 35.0,
    "traffic_state": "LOW",
    "severity": "LOW",
    "confidence": 0.91
  },
  {
    "frame_index": 21,
    "timestamp_sec": 0.7,
    "total_vehicles": 6,
    "cars": 3,
    "bikes": 2,
    "buses": 1,
    "trucks": 0,
    "density_score": 30.0,
    "traffic_state": "LOW",
    "severity": "LOW",
    "confidence": 0.91
  },
  {
    "frame_index": 24,
    "timestamp_sec": 0.8,
    "total_vehicles": 6,
    "cars": 3,
    "bikes": 2,
    "buses": 0,
    "trucks": 1,
    "density_score": 30.0,
    "traffic_state": "LOW",
    "severity": "LOW",
    "confidence": 0.91
  },
  {
    "frame_index": 27,
    "timestamp_sec": 0.9,
    "total_vehicles": 8,
    "cars": 6,
    "bikes": 1,
    "buses": 1,
    "trucks": 0,
    "density_score": 40.0,
    "traffic_state": "LOW",
    "severity": "LOW",
    "confidence": 0.91
  },
  {
    "frame_index": 30,
    "timestamp_sec": 1.0,
    "total_vehicles": 8,
    "cars": 6,
    "bikes": 1,
    "buses": 1,
    "trucks": 0,
    "density_score": 40.0,
    "traffic_state": "LOW",
    "severity": "LOW",
    "confidence": 0.91
  },
  {
    "frame_index": 33,
    "timestamp_sec": 1.1,
    "total_vehicles": 8,
    "cars": 5,
    "bikes": 2,
    "buses": 1,
    "trucks": 0,
    "density_score": 40.0,
    "traffic_state": "LOW",
    "severity": "LOW",
    "confidence": 0.91
  },
  {
    "frame_index": 36,
    "timestamp_sec": 1.2,
    "total_vehicles": 7,
    "cars": 5,
    "bikes": 1,
    "buses": 1,
    "trucks": 0,
    "density_score": 35.0,
    "traffic_state": "LOW",
    "severity": "LOW",
    "confidence": 0.91
  },
  {
    "frame_index": 39,
    "timestamp_sec": 1.3,
    "total_vehicles": 3,
    "cars": 3,
    "bikes": 0,
    "buses": 0,
    "trucks": 0,
    "density_score": 15.0,
    "traffic_state": "LOW",
    "severity": "LOW",
    "confidence": 0.91
  },
  {
    "frame_index": 42,
    "timestamp_sec": 1.4,
    "total_vehicles": 8,
    "cars": 5,
    "bikes": 3,
    "buses": 0,
    "trucks": 0,
    "density_score": 40.0,
    "traffic_state": "LOW",
    "severity": "LOW",
    "confidence": 0.91
  },
  {
    "frame_index": 45,
    "timestamp_sec": 1.5,
    "total_vehicles": 8,
    "cars": 7,
    "bikes": 1,
    "buses": 0,
    "trucks": 0,
    "density_score": 40.0,
    "traffic_state": "LOW",
    "severity": "LOW",
    "confidence": 0.91
  },
  {
    "frame_index": 48,
    "timestamp_sec": 1.6,
    "total_vehicles": 8,
    "cars": 6,
    "bikes": 2,
    "buses": 0,
    "trucks": 0,
    "density_score": 40.0,
    "traffic_state": "LOW",
    "severity": "LOW",
    "confidence": 0.91
  },
  {
    "frame_index": 51,
    "timestamp_sec": 1.7,
    "total_vehicles": 7,
    "cars": 6,
    "bikes": 1,
    "buses": 0,
    "trucks": 0,
    "density_score": 35.0,
    "traffic_state": "LOW",
    "severity": "LOW",
    "confidence": 0.91
  },
  {
    "frame_index": 54,
    "timestamp_sec": 1.8,
    "total_vehicles": 7,
    "cars": 6,
    "bikes": 1,
    "buses": 0,
    "trucks": 0,
    "density_score": 35.0,
    "traffic_state": "LOW",
    "severity": "LOW",
    "confidence": 0.91
  },
  {
    "frame_index": 57,
    "timestamp_sec": 1.9,
    "total_vehicles": 7,
    "cars": 5,
    "bikes": 1,
    "buses": 1,
    "trucks": 0,
    "density_score": 35.0,
    "traffic_state": "LOW",
    "severity": "LOW",
    "confidence": 0.91
  },
  {
    "frame_index": 60,
    "timestamp_sec": 2.0,
    "total_vehicles": 9,
    "cars": 5,
    "bikes": 3,
    "buses": 1,
    "trucks": 0,
    "density_score": 45.0,
    "traffic_state": "MEDIUM",
    "severity": "MEDIUM",
    "confidence": 0.91
  },
  {
    "frame_index": 63,
    "timestamp_sec": 2.1,
    "total_vehicles": 9,
    "cars": 6,
    "bikes": 2,
    "buses": 1,
    "trucks": 0,
    "density_score": 45.0,
    "traffic_state": "MEDIUM",
    "severity": "MEDIUM",
    "confidence": 0.91
  },
  {
    "frame_index": 66,
    "timestamp_sec": 2.2,
    "total_vehicles": 6,
    "cars": 6,
    "bikes": 0,
    "buses": 0,
    "trucks": 0,
    "density_score": 30.0,
    "traffic_state": "LOW",
    "severity": "LOW",
    "confidence": 0.91
  },
  {
    "frame_index": 69,
    "timestamp_sec": 2.3,
    "total_vehicles": 5,
    "cars": 3,
    "bikes": 0,
    "buses": 1,
    "trucks": 1,
    "density_score": 25.0,
    "traffic_state": "LOW",
    "severity": "LOW",
    "confidence": 0.91
  },
  {
    "frame_index": 72,
    "timestamp_sec": 2.4,
    "total_vehicles": 6,
    "cars": 2,
    "bikes": 2,
    "buses": 1,
    "trucks": 1,
    "density_score": 30.0,
    "traffic_state": "LOW",
    "severity": "LOW",
    "confidence": 0.91
  },
  {
    "frame_index": 75,
    "timestamp_sec": 2.5,
    "total_vehicles": 7,
    "cars": 5,
    "bikes": 1,
    "buses": 1,
    "trucks": 0,
    "density_score": 35.0,
    "traffic_state": "LOW",
    "severity": "LOW",
    "confidence": 0.91
  },
  {
    "frame_index": 78,
    "timestamp_sec": 2.6,
    "total_vehicles": 5,
    "cars": 4,
    "bikes": 0,
    "buses": 1,
    "trucks": 0,
    "density_score": 25.0,
    "traffic_state": "LOW",
    "severity": "LOW",
    "confidence": 0.91
  },
  {
    "frame_index": 81,
    "timestamp_sec": 2.7,
    "total_vehicles": 5,
    "cars": 4,
    "bikes": 0,
    "buses": 1,
    "trucks": 0,
    "density_score": 25.0,
    "traffic_state": "LOW",
    "severity": "LOW",
    "confidence": 0.91
  },
  {
    "frame_index": 84,
    "timestamp_sec": 2.8,
    "total_vehicles": 5,
    "cars": 4,
    "bikes": 0,
    "buses": 1,
    "trucks": 0,
    "density_score": 25.0,
    "traffic_state": "LOW",
    "severity": "LOW",
    "confidence": 0.91
  },
  {
    "frame_index": 87,
    "timestamp_sec": 2.9,
    "total_vehicles": 6,
    "cars": 5,
    "bikes": 0,
    "buses": 1,
    "trucks": 0,
    "density_score": 30.0,
    "traffic_state": "LOW",
    "severity": "LOW",
    "confidence": 0.91
  },
  {
    "frame_index": 90,
    "timestamp_sec": 3.0,
    "total_vehicles": 6,
    "cars": 4,
    "bikes": 1,
    "buses": 1,
    "trucks": 0,
    "density_score": 30.0,
    "traffic_state": "LOW",
    "severity": "LOW",
    "confidence": 0.91
  },
  {
    "frame_index": 93,
    "timestamp_sec": 3.1,
    "total_vehicles": 5,
    "cars": 4,
    "bikes": 0,
    "buses": 1,
    "trucks": 0,
    "density_score": 25.0,
    "traffic_state": "LOW",
    "severity": "LOW",
    "confidence": 0.91
  },
  {
    "frame_index": 96,
    "timestamp_sec": 3.2,
    "total_vehicles": 8,
    "cars": 5,
    "bikes": 1,
    "buses": 2,
    "trucks": 0,
    "density_score": 40.0,
    "traffic_state": "LOW",
    "severity": "LOW",
    "confidence": 0.91
  },
  {
    "frame_index": 99,
    "timestamp_sec": 3.3,
    "total_vehicles": 7,
    "cars": 4,
    "bikes": 1,
    "buses": 1,
    "trucks": 1,
    "density_score": 35.0,
    "traffic_state": "LOW",
    "severity": "LOW",
    "confidence": 0.91
  },
  {
    "frame_index": 102,
    "timestamp_sec": 3.4,
    "total_vehicles": 8,
    "cars": 4,
    "bikes": 2,
    "buses": 1,
    "trucks": 1,
    "density_score": 40.0,
    "traffic_state": "LOW",
    "severity": "LOW",
    "confidence": 0.91
  },
  {
    "frame_index": 105,
    "timestamp_sec": 3.5,
    "total_vehicles": 7,
    "cars": 5,
    "bikes": 0,
    "buses": 1,
    "trucks": 1,
    "density_score": 35.0,
    "traffic_state": "LOW",
    "severity": "LOW",
    "confidence": 0.91
  },
  {
    "frame_index": 108,
    "timestamp_sec": 3.6,
    "total_vehicles": 6,
    "cars": 2,
    "bikes": 2,
    "buses": 1,
    "trucks": 1,
    "density_score": 30.0,
    "traffic_state": "LOW",
    "severity": "LOW",
    "confidence": 0.91
  },
  {
    "frame_index": 111,
    "timestamp_sec": 3.7,
    "total_vehicles": 6,
    "cars": 3,
    "bikes": 1,
    "buses": 2,
    "trucks": 0,
    "density_score": 30.0,
    "traffic_state": "LOW",
    "severity": "LOW",
    "confidence": 0.91
  },
  {
    "frame_index": 114,
    "timestamp_sec": 3.8,
    "total_vehicles": 7,
    "cars": 3,
    "bikes": 2,
    "buses": 2,
    "trucks": 0,
    "density_score": 35.0,
    "traffic_state": "LOW",
    "severity": "LOW",
    "confidence": 0.91
  },
  {
    "frame_index": 117,
    "timestamp_sec": 3.9,
    "total_vehicles": 8,
    "cars": 3,
    "bikes": 2,
    "buses": 2,
    "trucks": 1,
    "density_score": 40.0,
    "traffic_state": "LOW",
    "severity": "LOW",
    "confidence": 0.91
  },
  {
    "frame_index": 120,
    "timestamp_sec": 4.0,
    "total_vehicles": 6,
    "cars": 3,
    "bikes": 1,
    "buses": 1,
    "trucks": 1,
    "density_score": 30.0,
    "traffic_state": "LOW",
    "severity": "LOW",
    "confidence": 0.91
  },
  {
    "frame_index": 123,
    "timestamp_sec": 4.1,
    "total_vehicles": 8,
    "cars": 4,
    "bikes": 2,
    "buses": 1,
    "trucks": 1,
    "density_score": 40.0,
    "traffic_state": "LOW",
    "severity": "LOW",
    "confidence": 0.91
  },
  {
    "frame_index": 126,
    "timestamp_sec": 4.2,
    "total_vehicles": 8,
    "cars": 4,
    "bikes": 3,
    "buses": 1,
    "trucks": 0,
    "density_score": 40.0,
    "traffic_state": "LOW",
    "severity": "LOW",
    "confidence": 0.91
  },
  {
    "frame_index": 129,
    "timestamp_sec": 4.3,
    "total_vehicles": 7,
    "cars": 5,
    "bikes": 1,
    "buses": 1,
    "trucks": 0,
    "density_score": 35.0,
    "traffic_state": "LOW",
    "severity": "LOW",
    "confidence": 0.91
  },
  {
    "frame_index": 132,
    "timestamp_sec": 4.4,
    "total_vehicles": 8,
    "cars": 4,
    "bikes": 3,
    "buses": 1,
    "trucks": 0,
    "density_score": 40.0,
    "traffic_state": "LOW",
    "severity": "LOW",
    "confidence": 0.91
  },
  {
    "frame_index": 135,
    "timestamp_sec": 4.5,
    "total_vehicles": 10,
    "cars": 5,
    "bikes": 3,
    "buses": 0,
    "trucks": 2,
    "density_score": 50.0,
    "traffic_state": "MEDIUM",
    "severity": "MEDIUM",
    "confidence": 0.91
  },
  {
    "frame_index": 138,
    "timestamp_sec": 4.6,
    "total_vehicles": 9,
    "cars": 5,
    "bikes": 2,
    "buses": 0,
    "trucks": 2,
    "density_score": 45.0,
    "traffic_state": "MEDIUM",
    "severity": "MEDIUM",
    "confidence": 0.91
  },
  {
    "frame_index": 141,
    "timestamp_sec": 4.7,
    "total_vehicles": 10,
    "cars": 5,
    "bikes": 2,
    "buses": 0,
    "trucks": 3,
    "density_score": 50.0,
    "traffic_state": "MEDIUM",
    "severity": "MEDIUM",
    "confidence": 0.91
  },
  {
    "frame_index": 144,
    "timestamp_sec": 4.8,
    "total_vehicles": 8,
    "cars": 4,
    "bikes": 2,
    "buses": 1,
    "trucks": 1,
    "density_score": 40.0,
    "traffic_state": "LOW",
    "severity": "LOW",
    "confidence": 0.91
  },
  {
    "frame_index": 147,
    "timestamp_sec": 4.9,
    "total_vehicles": 8,
    "cars": 5,
    "bikes": 1,
    "buses": 1,
    "trucks": 1,
    "density_score": 40.0,
    "traffic_state": "LOW",
    "severity": "LOW",
    "confidence": 0.91
  },
  {
    "frame_index": 150,
    "timestamp_sec": 5.01,
    "total_vehicles": 12,
    "cars": 6,
    "bikes": 4,
    "buses": 0,
    "trucks": 2,
    "density_score": 60.0,
    "traffic_state": "MEDIUM",
    "severity": "MEDIUM",
    "confidence": 0.91
  },
  {
    "frame_index": 153,
    "timestamp_sec": 5.11,
    "total_vehicles": 9,
    "cars": 5,
    "bikes": 2,
    "buses": 1,
    "trucks": 1,
    "density_score": 45.0,
    "traffic_state": "MEDIUM",
    "severity": "MEDIUM",
    "confidence": 0.91
  },
  {
    "frame_index": 156,
    "timestamp_sec": 5.21,
    "total_vehicles": 12,
    "cars": 6,
    "bikes": 3,
    "buses": 0,
    "trucks": 3,
    "density_score": 60.0,
    "traffic_state": "MEDIUM",
    "severity": "MEDIUM",
    "confidence": 0.91
  },
  {
    "frame_index": 159,
    "timestamp_sec": 5.31,
    "total_vehicles": 11,
    "cars": 6,
    "bikes": 2,
    "buses": 0,
    "trucks": 3,
    "density_score": 55.0,
    "traffic_state": "MEDIUM",
    "severity": "MEDIUM",
    "confidence": 0.91
  },
  {
    "frame_index": 162,
    "timestamp_sec": 5.41,
    "total_vehicles": 12,
    "cars": 6,
    "bikes": 3,
    "buses": 0,
    "trucks": 3,
    "density_score": 60.0,
    "traffic_state": "MEDIUM",
    "severity": "MEDIUM",
    "confidence": 0.91
  },
  {
    "frame_index": 165,
    "timestamp_sec": 5.51,
    "total_vehicles": 6,
    "cars": 4,
    "bikes": 0,
    "buses": 0,
    "trucks": 2,
    "density_score": 30.0,
    "traffic_state": "LOW",
    "severity": "LOW",
    "confidence": 0.91
  },
  {
    "frame_index": 168,
    "timestamp_sec": 5.61,
    "total_vehicles": 11,
    "cars": 6,
    "bikes": 3,
    "buses": 1,
    "trucks": 1,
    "density_score": 55.0,
    "traffic_state": "MEDIUM",
    "severity": "MEDIUM",
    "confidence": 0.91
  },
  {
    "frame_index": 171,
    "timestamp_sec": 5.71,
    "total_vehicles": 11,
    "cars": 8,
    "bikes": 1,
    "buses": 1,
    "trucks": 1,
    "density_score": 55.0,
    "traffic_state": "MEDIUM",
    "severity": "MEDIUM",
    "confidence": 0.91
  },
  {
    "frame_index": 174,
    "timestamp_sec": 5.81,
    "total_vehicles": 15,
    "cars": 11,
    "bikes": 3,
    "buses": 0,
    "trucks": 1,
    "density_score": 75.0,
    "traffic_state": "MEDIUM",
    "severity": "MEDIUM",
    "confidence": 0.91
  },
  {
    "frame_index": 177,
    "timestamp_sec": 5.91,
    "total_vehicles": 13,
    "cars": 9,
    "bikes": 3,
    "buses": 0,
    "trucks": 1,
    "density_score": 65.0,
    "traffic_state": "MEDIUM",
    "severity": "MEDIUM",
    "confidence": 0.91
  },
  {
    "frame_index": 180,
    "timestamp_sec": 6.01,
    "total_vehicles": 10,
    "cars": 7,
    "bikes": 2,
    "buses": 0,
    "trucks": 1,
    "density_score": 50.0,
    "traffic_state": "MEDIUM",
    "severity": "MEDIUM",
    "confidence": 0.91
  },
  {
    "frame_index": 183,
    "timestamp_sec": 6.11,
    "total_vehicles": 11,
    "cars": 6,
    "bikes": 4,
    "buses": 0,
    "trucks": 1,
    "density_score": 55.0,
    "traffic_state": "MEDIUM",
    "severity": "MEDIUM",
    "confidence": 0.91
  },
  {
    "frame_index": 186,
    "timestamp_sec": 6.21,
    "total_vehicles": 9,
    "cars": 4,
    "bikes": 4,
    "buses": 0,
    "trucks": 1,
    "density_score": 45.0,
    "traffic_state": "MEDIUM",
    "severity": "MEDIUM",
    "confidence": 0.91
  },
  {
    "frame_index": 189,
    "timestamp_sec": 6.31,
    "total_vehicles": 8,
    "cars": 5,
    "bikes": 2,
    "buses": 0,
    "trucks": 1,
    "density_score": 40.0,
    "traffic_state": "LOW",
    "severity": "LOW",
    "confidence": 0.91
  },
  {
    "frame_index": 192,
    "timestamp_sec": 6.41,
    "total_vehicles": 10,
    "cars": 6,
    "bikes": 3,
    "buses": 0,
    "trucks": 1,
    "density_score": 50.0,
    "traffic_state": "MEDIUM",
    "severity": "MEDIUM",
    "confidence": 0.91
  },
  {
    "frame_index": 195,
    "timestamp_sec": 6.51,
    "total_vehicles": 8,
    "cars": 5,
    "bikes": 2,
    "buses": 0,
    "trucks": 1,
    "density_score": 40.0,
    "traffic_state": "LOW",
    "severity": "LOW",
    "confidence": 0.91
  },
  {
    "frame_index": 198,
    "timestamp_sec": 6.61,
    "total_vehicles": 8,
    "cars": 4,
    "bikes": 3,
    "buses": 0,
    "trucks": 1,
    "density_score": 40.0,
    "traffic_state": "LOW",
    "severity": "LOW",
    "confidence": 0.91
  },
  {
    "frame_index": 201,
    "timestamp_sec": 6.71,
    "total_vehicles": 9,
    "cars": 4,
    "bikes": 4,
    "buses": 0,
    "trucks": 1,
    "density_score": 45.0,
    "traffic_state": "MEDIUM",
    "severity": "MEDIUM",
    "confidence": 0.91
  },
  {
    "frame_index": 204,
    "timestamp_sec": 6.81,
    "total_vehicles": 9,
    "cars": 3,
    "bikes": 5,
    "buses": 0,
    "trucks": 1,
    "density_score": 45.0,
    "traffic_state": "MEDIUM",
    "severity": "MEDIUM",
    "confidence": 0.91
  },
  {
    "frame_index": 207,
    "timestamp_sec": 6.91,
    "total_vehicles": 9,
    "cars": 5,
    "bikes": 3,
    "buses": 0,
    "trucks": 1,
    "density_score": 45.0,
    "traffic_state": "MEDIUM",
    "severity": "MEDIUM",
    "confidence": 0.91
  },
  {
    "frame_index": 210,
    "timestamp_sec": 7.01,
    "total_vehicles": 10,
    "cars": 5,
    "bikes": 4,
    "buses": 0,
    "trucks": 1,
    "density_score": 50.0,
    "traffic_state": "MEDIUM",
    "severity": "MEDIUM",
    "confidence": 0.91
  },
  {
    "frame_index": 213,
    "timestamp_sec": 7.11,
    "total_vehicles": 10,
    "cars": 4,
    "bikes": 5,
    "buses": 0,
    "trucks": 1,
    "density_score": 50.0,
    "traffic_state": "MEDIUM",
    "severity": "MEDIUM",
    "confidence": 0.91
  },
  {
    "frame_index": 216,
    "timestamp_sec": 7.21,
    "total_vehicles": 9,
    "cars": 5,
    "bikes": 3,
    "buses": 1,
    "trucks": 0,
    "density_score": 45.0,
    "traffic_state": "MEDIUM",
    "severity": "MEDIUM",
    "confidence": 0.91
  },
  {
    "frame_index": 219,
    "timestamp_sec": 7.31,
    "total_vehicles": 10,
    "cars": 4,
    "bikes": 5,
    "buses": 1,
    "trucks": 0,
    "density_score": 50.0,
    "traffic_state": "MEDIUM",
    "severity": "MEDIUM",
    "confidence": 0.91
  },
  {
    "frame_index": 222,
    "timestamp_sec": 7.41,
    "total_vehicles": 8,
    "cars": 4,
    "bikes": 3,
    "buses": 1,
    "trucks": 0,
    "density_score": 40.0,
    "traffic_state": "LOW",
    "severity": "LOW",
    "confidence": 0.91
  },
  {
    "frame_index": 225,
    "timestamp_sec": 7.51,
    "total_vehicles": 9,
    "cars": 6,
    "bikes": 2,
    "buses": 0,
    "trucks": 1,
    "density_score": 45.0,
    "traffic_state": "MEDIUM",
    "severity": "MEDIUM",
    "confidence": 0.91
  },
  {
    "frame_index": 228,
    "timestamp_sec": 7.61,
    "total_vehicles": 6,
    "cars": 4,
    "bikes": 0,
    "buses": 0,
    "trucks": 2,
    "density_score": 30.0,
    "traffic_state": "LOW",
    "severity": "LOW",
    "confidence": 0.91
  },
  {
    "frame_index": 231,
    "timestamp_sec": 7.71,
    "total_vehicles": 8,
    "cars": 6,
    "bikes": 1,
    "buses": 0,
    "trucks": 1,
    "density_score": 40.0,
    "traffic_state": "LOW",
    "severity": "LOW",
    "confidence": 0.91
  },
  {
    "frame_index": 234,
    "timestamp_sec": 7.81,
    "total_vehicles": 7,
    "cars": 4,
    "bikes": 1,
    "buses": 0,
    "trucks": 2,
    "density_score": 35.0,
    "traffic_state": "LOW",
    "severity": "LOW",
    "confidence": 0.91
  },
  {
    "frame_index": 237,
    "timestamp_sec": 7.91,
    "total_vehicles": 7,
    "cars": 5,
    "bikes": 1,
    "buses": 0,
    "trucks": 1,
    "density_score": 35.0,
    "traffic_state": "LOW",
    "severity": "LOW",
    "confidence": 0.91
  },
  {
    "frame_index": 240,
    "timestamp_sec": 8.01,
    "total_vehicles": 7,
    "cars": 4,
    "bikes": 1,
    "buses": 1,
    "trucks": 1,
    "density_score": 35.0,
    "traffic_state": "LOW",
    "severity": "LOW",
    "confidence": 0.91
  },
  {
    "frame_index": 243,
    "timestamp_sec": 8.11,
    "total_vehicles": 7,
    "cars": 3,
    "bikes": 2,
    "buses": 1,
    "trucks": 1,
    "density_score": 35.0,
    "traffic_state": "LOW",
    "severity": "LOW",
    "confidence": 0.91
  },
  {
    "frame_index": 246,
    "timestamp_sec": 8.21,
    "total_vehicles": 6,
    "cars": 4,
    "bikes": 1,
    "buses": 0,
    "trucks": 1,
    "density_score": 30.0,
    "traffic_state": "LOW",
    "severity": "LOW",
    "confidence": 0.91
  },
  {
    "frame_index": 249,
    "timestamp_sec": 8.31,
    "total_vehicles": 9,
    "cars": 6,
    "bikes": 2,
    "buses": 0,
    "trucks": 1,
    "density_score": 45.0,
    "traffic_state": "MEDIUM",
    "severity": "MEDIUM",
    "confidence": 0.91
  },
  {
    "frame_index": 252,
    "timestamp_sec": 8.41,
    "total_vehicles": 8,
    "cars": 6,
    "bikes": 1,
    "buses": 0,
    "trucks": 1,
    "density_score": 40.0,
    "traffic_state": "LOW",
    "severity": "LOW",
    "confidence": 0.91
  },
  {
    "frame_index": 255,
    "timestamp_sec": 8.51,
    "total_vehicles": 8,
    "cars": 6,
    "bikes": 1,
    "buses": 0,
    "trucks": 1,
    "density_score": 40.0,
    "traffic_state": "LOW",
    "severity": "LOW",
    "confidence": 0.91
  },
  {
    "frame_index": 258,
    "timestamp_sec": 8.61,
    "total_vehicles": 7,
    "cars": 5,
    "bikes": 1,
    "buses": 0,
    "trucks": 1,
    "density_score": 35.0,
    "traffic_state": "LOW",
    "severity": "LOW",
    "confidence": 0.91
  },
  {
    "frame_index": 261,
    "timestamp_sec": 8.71,
    "total_vehicles": 7,
    "cars": 5,
    "bikes": 1,
    "buses": 0,
    "trucks": 1,
    "density_score": 35.0,
    "traffic_state": "LOW",
    "severity": "LOW",
    "confidence": 0.91
  },
  {
    "frame_index": 264,
    "timestamp_sec": 8.81,
    "total_vehicles": 10,
    "cars": 7,
    "bikes": 2,
    "buses": 0,
    "trucks": 1,
    "density_score": 50.0,
    "traffic_state": "MEDIUM",
    "severity": "MEDIUM",
    "confidence": 0.91
  },
  {
    "frame_index": 267,
    "timestamp_sec": 8.91,
    "total_vehicles": 10,
    "cars": 8,
    "bikes": 1,
    "buses": 0,
    "trucks": 1,
    "density_score": 50.0,
    "traffic_state": "MEDIUM",
    "severity": "MEDIUM",
    "confidence": 0.91
  },
  {
    "frame_index": 270,
    "timestamp_sec": 9.01,
    "total_vehicles": 8,
    "cars": 6,
    "bikes": 1,
    "buses": 0,
    "trucks": 1,
    "density_score": 40.0,
    "traffic_state": "LOW",
    "severity": "LOW",
    "confidence": 0.91
  },
  {
    "frame_index": 273,
    "timestamp_sec": 9.11,
    "total_vehicles": 8,
    "cars": 5,
    "bikes": 2,
    "buses": 0,
    "trucks": 1,
    "density_score": 40.0,
    "traffic_state": "LOW",
    "severity": "LOW",
    "confidence": 0.91
  },
  {
    "frame_index": 276,
    "timestamp_sec": 9.21,
    "total_vehicles": 10,
    "cars": 8,
    "bikes": 1,
    "buses": 1,
    "trucks": 0,
    "density_score": 50.0,
    "traffic_state": "MEDIUM",
    "severity": "MEDIUM",
    "confidence": 0.91
  },
  {
    "frame_index": 279,
    "timestamp_sec": 9.31,
    "total_vehicles": 8,
    "cars": 4,
    "bikes": 2,
    "buses": 0,
    "trucks": 2,
    "density_score": 40.0,
    "traffic_state": "LOW",
    "severity": "LOW",
    "confidence": 0.91
  },
  {
    "frame_index": 282,
    "timestamp_sec": 9.41,
    "total_vehicles": 8,
    "cars": 4,
    "bikes": 2,
    "buses": 0,
    "trucks": 2,
    "density_score": 40.0,
    "traffic_state": "LOW",
    "severity": "LOW",
    "confidence": 0.91
  },
  {
    "frame_index": 285,
    "timestamp_sec": 9.51,
    "total_vehicles": 5,
    "cars": 4,
    "bikes": 1,
    "buses": 0,
    "trucks": 0,
    "density_score": 25.0,
    "traffic_state": "LOW",
    "severity": "LOW",
    "confidence": 0.91
  },
  {
    "frame_index": 288,
    "timestamp_sec": 9.61,
    "total_vehicles": 3,
    "cars": 2,
    "bikes": 1,
    "buses": 0,
    "trucks": 0,
    "density_score": 15.0,
    "traffic_state": "LOW",
    "severity": "LOW",
    "confidence": 0.91
  },
  {
    "frame_index": 291,
    "timestamp_sec": 9.71,
    "total_vehicles": 8,
    "cars": 4,
    "bikes": 3,
    "buses": 0,
    "trucks": 1,
    "density_score": 40.0,
    "traffic_state": "LOW",
    "severity": "LOW",
    "confidence": 0.91
  },
  {
    "frame_index": 294,
    "timestamp_sec": 9.81,
    "total_vehicles": 8,
    "cars": 4,
    "bikes": 4,
    "buses": 0,
    "trucks": 0,
    "density_score": 40.0,
    "traffic_state": "LOW",
    "severity": "LOW",
    "confidence": 0.91
  },
  {
    "frame_index": 297,
    "timestamp_sec": 9.91,
    "total_vehicles": 7,
    "cars": 4,
    "bikes": 3,
    "buses": 0,
    "trucks": 0,
    "density_score": 35.0,
    "traffic_state": "LOW",
    "severity": "LOW",
    "confidence": 0.91
  },
  {
    "frame_index": 300,
    "timestamp_sec": 10.01,
    "total_vehicles": 6,
    "cars": 5,
    "bikes": 1,
    "buses": 0,
    "trucks": 0,
    "density_score": 30.0,
    "traffic_state": "LOW",
    "severity": "LOW",
    "confidence": 0.91
  },
  {
    "frame_index": 303,
    "timestamp_sec": 10.11,
    "total_vehicles": 5,
    "cars": 2,
    "bikes": 3,
    "buses": 0,
    "trucks": 0,
    "density_score": 25.0,
    "traffic_state": "LOW",
    "severity": "LOW",
    "confidence": 0.91
  },
  {
    "frame_index": 306,
    "timestamp_sec": 10.21,
    "total_vehicles": 6,
    "cars": 2,
    "bikes": 3,
    "buses": 0,
    "trucks": 1,
    "density_score": 30.0,
    "traffic_state": "LOW",
    "severity": "LOW",
    "confidence": 0.91
  },
  {
    "frame_index": 309,
    "timestamp_sec": 10.31,
    "total_vehicles": 6,
    "cars": 2,
    "bikes": 3,
    "buses": 0,
    "trucks": 1,
    "density_score": 30.0,
    "traffic_state": "LOW",
    "severity": "LOW",
    "confidence": 0.91
  },
  {
    "frame_index": 312,
    "timestamp_sec": 10.41,
    "total_vehicles": 7,
    "cars": 1,
    "bikes": 4,
    "buses": 0,
    "trucks": 2,
    "density_score": 35.0,
    "traffic_state": "LOW",
    "severity": "LOW",
    "confidence": 0.91
  },
  {
    "frame_index": 315,
    "timestamp_sec": 10.51,
    "total_vehicles": 4,
    "cars": 1,
    "bikes": 1,
    "buses": 0,
    "trucks": 2,
    "density_score": 20.0,
    "traffic_state": "LOW",
    "severity": "LOW",
    "confidence": 0.91
  },
  {
    "frame_index": 318,
    "timestamp_sec": 10.61,
    "total_vehicles": 6,
    "cars": 1,
    "bikes": 3,
    "buses": 0,
    "trucks": 2,
    "density_score": 30.0,
    "traffic_state": "LOW",
    "severity": "LOW",
    "confidence": 0.91
  },
  {
    "frame_index": 321,
    "timestamp_sec": 10.71,
    "total_vehicles": 5,
    "cars": 2,
    "bikes": 1,
    "buses": 0,
    "trucks": 2,
    "density_score": 25.0,
    "traffic_state": "LOW",
    "severity": "LOW",
    "confidence": 0.91
  },
  {
    "frame_index": 324,
    "timestamp_sec": 10.81,
    "total_vehicles": 6,
    "cars": 1,
    "bikes": 3,
    "buses": 0,
    "trucks": 2,
    "density_score": 30.0,
    "traffic_state": "LOW",
    "severity": "LOW",
    "confidence": 0.91
  },
  {
    "frame_index": 327,
    "timestamp_sec": 10.91,
    "total_vehicles": 5,
    "cars": 1,
    "bikes": 2,
    "buses": 0,
    "trucks": 2,
    "density_score": 25.0,
    "traffic_state": "LOW",
    "severity": "LOW",
    "confidence": 0.91
  },
  {
    "frame_index": 330,
    "timestamp_sec": 11.01,
    "total_vehicles": 7,
    "cars": 1,
    "bikes": 4,
    "buses": 0,
    "trucks": 2,
    "density_score": 35.0,
    "traffic_state": "LOW",
    "severity": "LOW",
    "confidence": 0.91
  },
  {
    "frame_index": 333,
    "timestamp_sec": 11.11,
    "total_vehicles": 8,
    "cars": 2,
    "bikes": 4,
    "buses": 0,
    "trucks": 2,
    "density_score": 40.0,
    "traffic_state": "LOW",
    "severity": "LOW",
    "confidence": 0.91
  },
  {
    "frame_index": 336,
    "timestamp_sec": 11.21,
    "total_vehicles": 12,
    "cars": 6,
    "bikes": 4,
    "buses": 0,
    "trucks": 2,
    "density_score": 60.0,
    "traffic_state": "MEDIUM",
    "severity": "MEDIUM",
    "confidence": 0.91
  },
  {
    "frame_index": 339,
    "timestamp_sec": 11.31,
    "total_vehicles": 13,
    "cars": 4,
    "bikes": 7,
    "buses": 0,
    "trucks": 2,
    "density_score": 65.0,
    "traffic_state": "MEDIUM",
    "severity": "MEDIUM",
    "confidence": 0.91
  },
  {
    "frame_index": 342,
    "timestamp_sec": 11.41,
    "total_vehicles": 10,
    "cars": 7,
    "bikes": 2,
    "buses": 0,
    "trucks": 1,
    "density_score": 50.0,
    "traffic_state": "MEDIUM",
    "severity": "MEDIUM",
    "confidence": 0.91
  },
  {
    "frame_index": 345,
    "timestamp_sec": 11.51,
    "total_vehicles": 7,
    "cars": 3,
    "bikes": 3,
    "buses": 0,
    "trucks": 1,
    "density_score": 35.0,
    "traffic_state": "LOW",
    "severity": "LOW",
    "confidence": 0.91
  },
  {
    "frame_index": 348,
    "timestamp_sec": 11.61,
    "total_vehicles": 5,
    "cars": 2,
    "bikes": 3,
    "buses": 0,
    "trucks": 0,
    "density_score": 25.0,
    "traffic_state": "LOW",
    "severity": "LOW",
    "confidence": 0.91
  },
  {
    "frame_index": 351,
    "timestamp_sec": 11.71,
    "total_vehicles": 9,
    "cars": 6,
    "bikes": 3,
    "buses": 0,
    "trucks": 0,
    "density_score": 45.0,
    "traffic_state": "MEDIUM",
    "severity": "MEDIUM",
    "confidence": 0.91
  },
  {
    "frame_index": 354,
    "timestamp_sec": 11.81,
    "total_vehicles": 9,
    "cars": 6,
    "bikes": 2,
    "buses": 0,
    "trucks": 1,
    "density_score": 45.0,
    "traffic_state": "MEDIUM",
    "severity": "MEDIUM",
    "confidence": 0.91
  },
  {
    "frame_index": 357,
    "timestamp_sec": 11.91,
    "total_vehicles": 5,
    "cars": 3,
    "bikes": 2,
    "buses": 0,
    "trucks": 0,
    "density_score": 25.0,
    "traffic_state": "LOW",
    "severity": "LOW",
    "confidence": 0.91
  },
  {
    "frame_index": 360,
    "timestamp_sec": 12.01,
    "total_vehicles": 6,
    "cars": 5,
    "bikes": 1,
    "buses": 0,
    "trucks": 0,
    "density_score": 30.0,
    "traffic_state": "LOW",
    "severity": "LOW",
    "confidence": 0.91
  },
  {
    "frame_index": 363,
    "timestamp_sec": 12.11,
    "total_vehicles": 8,
    "cars": 5,
    "bikes": 3,
    "buses": 0,
    "trucks": 0,
    "density_score": 40.0,
    "traffic_state": "LOW",
    "severity": "LOW",
    "confidence": 0.91
  },
  {
    "frame_index": 366,
    "timestamp_sec": 12.21,
    "total_vehicles": 9,
    "cars": 6,
    "bikes": 2,
    "buses": 0,
    "trucks": 1,
    "density_score": 45.0,
    "traffic_state": "MEDIUM",
    "severity": "MEDIUM",
    "confidence": 0.91
  },
  {
    "frame_index": 369,
    "timestamp_sec": 12.31,
    "total_vehicles": 9,
    "cars": 5,
    "bikes": 3,
    "buses": 0,
    "trucks": 1,
    "density_score": 45.0,
    "traffic_state": "MEDIUM",
    "severity": "MEDIUM",
    "confidence": 0.91
  },
  {
    "frame_index": 372,
    "timestamp_sec": 12.41,
    "total_vehicles": 7,
    "cars": 3,
    "bikes": 3,
    "buses": 0,
    "trucks": 1,
    "density_score": 35.0,
    "traffic_state": "LOW",
    "severity": "LOW",
    "confidence": 0.91
  },
  {
    "frame_index": 375,
    "timestamp_sec": 12.51,
    "total_vehicles": 7,
    "cars": 3,
    "bikes": 3,
    "buses": 0,
    "trucks": 1,
    "density_score": 35.0,
    "traffic_state": "LOW",
    "severity": "LOW",
    "confidence": 0.91
  },
  {
    "frame_index": 378,
    "timestamp_sec": 12.61,
    "total_vehicles": 4,
    "cars": 3,
    "bikes": 0,
    "buses": 0,
    "trucks": 1,
    "density_score": 20.0,
    "traffic_state": "LOW",
    "severity": "LOW",
    "confidence": 0.91
  },
  {
    "frame_index": 381,
    "timestamp_sec": 12.71,
    "total_vehicles": 7,
    "cars": 4,
    "bikes": 2,
    "buses": 0,
    "trucks": 1,
    "density_score": 35.0,
    "traffic_state": "LOW",
    "severity": "LOW",
    "confidence": 0.91
  },
  {
    "frame_index": 384,
    "timestamp_sec": 12.81,
    "total_vehicles": 8,
    "cars": 5,
    "bikes": 2,
    "buses": 0,
    "trucks": 1,
    "density_score": 40.0,
    "traffic_state": "LOW",
    "severity": "LOW",
    "confidence": 0.91
  },
  {
    "frame_index": 387,
    "timestamp_sec": 12.91,
    "total_vehicles": 7,
    "cars": 5,
    "bikes": 1,
    "buses": 0,
    "trucks": 1,
    "density_score": 35.0,
    "traffic_state": "LOW",
    "severity": "LOW",
    "confidence": 0.91
  },
  {
    "frame_index": 390,
    "timestamp_sec": 13.01,
    "total_vehicles": 8,
    "cars": 6,
    "bikes": 1,
    "buses": 0,
    "trucks": 1,
    "density_score": 40.0,
    "traffic_state": "LOW",
    "severity": "LOW",
    "confidence": 0.91
  },
  {
    "frame_index": 393,
    "timestamp_sec": 13.11,
    "total_vehicles": 6,
    "cars": 4,
    "bikes": 1,
    "buses": 1,
    "trucks": 0,
    "density_score": 30.0,
    "traffic_state": "LOW",
    "severity": "LOW",
    "confidence": 0.91
  },
  {
    "frame_index": 396,
    "timestamp_sec": 13.21,
    "total_vehicles": 7,
    "cars": 4,
    "bikes": 2,
    "buses": 0,
    "trucks": 1,
    "density_score": 35.0,
    "traffic_state": "LOW",
    "severity": "LOW",
    "confidence": 0.91
  },
  {
    "frame_index": 399,
    "timestamp_sec": 13.31,
    "total_vehicles": 6,
    "cars": 3,
    "bikes": 2,
    "buses": 0,
    "trucks": 1,
    "density_score": 30.0,
    "traffic_state": "LOW",
    "severity": "LOW",
    "confidence": 0.91
  },
  {
    "frame_index": 402,
    "timestamp_sec": 13.41,
    "total_vehicles": 10,
    "cars": 5,
    "bikes": 4,
    "buses": 0,
    "trucks": 1,
    "density_score": 50.0,
    "traffic_state": "MEDIUM",
    "severity": "MEDIUM",
    "confidence": 0.91
  },
  {
    "frame_index": 405,
    "timestamp_sec": 13.51,
    "total_vehicles": 9,
    "cars": 4,
    "bikes": 4,
    "buses": 1,
    "trucks": 0,
    "density_score": 45.0,
    "traffic_state": "MEDIUM",
    "severity": "MEDIUM",
    "confidence": 0.91
  },
  {
    "frame_index": 408,
    "timestamp_sec": 13.61,
    "total_vehicles": 7,
    "cars": 3,
    "bikes": 3,
    "buses": 1,
    "trucks": 0,
    "density_score": 35.0,
    "traffic_state": "LOW",
    "severity": "LOW",
    "confidence": 0.91
  },
  {
    "frame_index": 411,
    "timestamp_sec": 13.71,
    "total_vehicles": 8,
    "cars": 4,
    "bikes": 3,
    "buses": 0,
    "trucks": 1,
    "density_score": 40.0,
    "traffic_state": "LOW",
    "severity": "LOW",
    "confidence": 0.91
  },
  {
    "frame_index": 414,
    "timestamp_sec": 13.81,
    "total_vehicles": 9,
    "cars": 5,
    "bikes": 3,
    "buses": 0,
    "trucks": 1,
    "density_score": 45.0,
    "traffic_state": "MEDIUM",
    "severity": "MEDIUM",
    "confidence": 0.91
  },
  {
    "frame_index": 417,
    "timestamp_sec": 13.91,
    "total_vehicles": 9,
    "cars": 5,
    "bikes": 3,
    "buses": 0,
    "trucks": 1,
    "density_score": 45.0,
    "traffic_state": "MEDIUM",
    "severity": "MEDIUM",
    "confidence": 0.91
  },
  {
    "frame_index": 420,
    "timestamp_sec": 14.01,
    "total_vehicles": 8,
    "cars": 5,
    "bikes": 2,
    "buses": 0,
    "trucks": 1,
    "density_score": 40.0,
    "traffic_state": "LOW",
    "severity": "LOW",
    "confidence": 0.91
  },
  {
    "frame_index": 423,
    "timestamp_sec": 14.11,
    "total_vehicles": 10,
    "cars": 6,
    "bikes": 2,
    "buses": 1,
    "trucks": 1,
    "density_score": 50.0,
    "traffic_state": "MEDIUM",
    "severity": "MEDIUM",
    "confidence": 0.91
  },
  {
    "frame_index": 426,
    "timestamp_sec": 14.21,
    "total_vehicles": 12,
    "cars": 10,
    "bikes": 1,
    "buses": 1,
    "trucks": 0,
    "density_score": 60.0,
    "traffic_state": "MEDIUM",
    "severity": "MEDIUM",
    "confidence": 0.91
  },
  {
    "frame_index": 429,
    "timestamp_sec": 14.31,
    "total_vehicles": 11,
    "cars": 7,
    "bikes": 2,
    "buses": 1,
    "trucks": 1,
    "density_score": 55.0,
    "traffic_state": "MEDIUM",
    "severity": "MEDIUM",
    "confidence": 0.91
  },
  {
    "frame_index": 432,
    "timestamp_sec": 14.41,
    "total_vehicles": 9,
    "cars": 5,
    "bikes": 2,
    "buses": 1,
    "trucks": 1,
    "density_score": 45.0,
    "traffic_state": "MEDIUM",
    "severity": "MEDIUM",
    "confidence": 0.91
  },
  {
    "frame_index": 435,
    "timestamp_sec": 14.51,
    "total_vehicles": 9,
    "cars": 6,
    "bikes": 1,
    "buses": 1,
    "trucks": 1,
    "density_score": 45.0,
    "traffic_state": "MEDIUM",
    "severity": "MEDIUM",
    "confidence": 0.91
  },
  {
    "frame_index": 438,
    "timestamp_sec": 14.61,
    "total_vehicles": 11,
    "cars": 6,
    "bikes": 3,
    "buses": 1,
    "trucks": 1,
    "density_score": 55.0,
    "traffic_state": "MEDIUM",
    "severity": "MEDIUM",
    "confidence": 0.91
  },
  {
    "frame_index": 441,
    "timestamp_sec": 14.71,
    "total_vehicles": 12,
    "cars": 5,
    "bikes": 5,
    "buses": 1,
    "trucks": 1,
    "density_score": 60.0,
    "traffic_state": "MEDIUM",
    "severity": "MEDIUM",
    "confidence": 0.91
  },
  {
    "frame_index": 444,
    "timestamp_sec": 14.81,
    "total_vehicles": 12,
    "cars": 5,
    "bikes": 5,
    "buses": 1,
    "trucks": 1,
    "density_score": 60.0,
    "traffic_state": "MEDIUM",
    "severity": "MEDIUM",
    "confidence": 0.91
  },
  {
    "frame_index": 447,
    "timestamp_sec": 14.91,
    "total_vehicles": 10,
    "cars": 5,
    "bikes": 3,
    "buses": 1,
    "trucks": 1,
    "density_score": 50.0,
    "traffic_state": "MEDIUM",
    "severity": "MEDIUM",
    "confidence": 0.91
  },
  {
    "frame_index": 450,
    "timestamp_sec": 15.02,
    "total_vehicles": 9,
    "cars": 5,
    "bikes": 2,
    "buses": 1,
    "trucks": 1,
    "density_score": 45.0,
    "traffic_state": "MEDIUM",
    "severity": "MEDIUM",
    "confidence": 0.91
  },
  {
    "frame_index": 453,
    "timestamp_sec": 15.12,
    "total_vehicles": 8,
    "cars": 4,
    "bikes": 2,
    "buses": 1,
    "trucks": 1,
    "density_score": 40.0,
    "traffic_state": "LOW",
    "severity": "LOW",
    "confidence": 0.91
  },
  {
    "frame_index": 456,
    "timestamp_sec": 15.22,
    "total_vehicles": 11,
    "cars": 7,
    "bikes": 2,
    "buses": 1,
    "trucks": 1,
    "density_score": 55.0,
    "traffic_state": "MEDIUM",
    "severity": "MEDIUM",
    "confidence": 0.91
  },
  {
    "frame_index": 459,
    "timestamp_sec": 15.32,
    "total_vehicles": 10,
    "cars": 6,
    "bikes": 2,
    "buses": 1,
    "trucks": 1,
    "density_score": 50.0,
    "traffic_state": "MEDIUM",
    "severity": "MEDIUM",
    "confidence": 0.91
  },
  {
    "frame_index": 462,
    "timestamp_sec": 15.42,
    "total_vehicles": 10,
    "cars": 7,
    "bikes": 2,
    "buses": 1,
    "trucks": 0,
    "density_score": 50.0,
    "traffic_state": "MEDIUM",
    "severity": "MEDIUM",
    "confidence": 0.91
  },
  {
    "frame_index": 465,
    "timestamp_sec": 15.52,
    "total_vehicles": 10,
    "cars": 5,
    "bikes": 3,
    "buses": 1,
    "trucks": 1,
    "density_score": 50.0,
    "traffic_state": "MEDIUM",
    "severity": "MEDIUM",
    "confidence": 0.91
  },
  {
    "frame_index": 468,
    "timestamp_sec": 15.62,
    "total_vehicles": 7,
    "cars": 5,
    "bikes": 1,
    "buses": 1,
    "trucks": 0,
    "density_score": 35.0,
    "traffic_state": "LOW",
    "severity": "LOW",
    "confidence": 0.91
  },
  {
    "frame_index": 471,
    "timestamp_sec": 15.72,
    "total_vehicles": 6,
    "cars": 3,
    "bikes": 1,
    "buses": 1,
    "trucks": 1,
    "density_score": 30.0,
    "traffic_state": "LOW",
    "severity": "LOW",
    "confidence": 0.91
  },
  {
    "frame_index": 474,
    "timestamp_sec": 15.82,
    "total_vehicles": 5,
    "cars": 4,
    "bikes": 0,
    "buses": 1,
    "trucks": 0,
    "density_score": 25.0,
    "traffic_state": "LOW",
    "severity": "LOW",
    "confidence": 0.91
  },
  {
    "frame_index": 477,
    "timestamp_sec": 15.92,
    "total_vehicles": 6,
    "cars": 4,
    "bikes": 0,
    "buses": 1,
    "trucks": 1,
    "density_score": 30.0,
    "traffic_state": "LOW",
    "severity": "LOW",
    "confidence": 0.91
  },
  {
    "frame_index": 480,
    "timestamp_sec": 16.02,
    "total_vehicles": 6,
    "cars": 3,
    "bikes": 1,
    "buses": 0,
    "trucks": 2,
    "density_score": 30.0,
    "traffic_state": "LOW",
    "severity": "LOW",
    "confidence": 0.91
  },
  {
    "frame_index": 483,
    "timestamp_sec": 16.12,
    "total_vehicles": 9,
    "cars": 6,
    "bikes": 1,
    "buses": 0,
    "trucks": 2,
    "density_score": 45.0,
    "traffic_state": "MEDIUM",
    "severity": "MEDIUM",
    "confidence": 0.91
  },
  {
    "frame_index": 486,
    "timestamp_sec": 16.22,
    "total_vehicles": 9,
    "cars": 5,
    "bikes": 3,
    "buses": 0,
    "trucks": 1,
    "density_score": 45.0,
    "traffic_state": "MEDIUM",
    "severity": "MEDIUM",
    "confidence": 0.91
  },
  {
    "frame_index": 489,
    "timestamp_sec": 16.32,
    "total_vehicles": 8,
    "cars": 5,
    "bikes": 2,
    "buses": 1,
    "trucks": 0,
    "density_score": 40.0,
    "traffic_state": "LOW",
    "severity": "LOW",
    "confidence": 0.91
  },
  {
    "frame_index": 492,
    "timestamp_sec": 16.42,
    "total_vehicles": 9,
    "cars": 4,
    "bikes": 3,
    "buses": 1,
    "trucks": 1,
    "density_score": 45.0,
    "traffic_state": "MEDIUM",
    "severity": "MEDIUM",
    "confidence": 0.91
  },
  {
    "frame_index": 495,
    "timestamp_sec": 16.52,
    "total_vehicles": 8,
    "cars": 5,
    "bikes": 3,
    "buses": 0,
    "trucks": 0,
    "density_score": 40.0,
    "traffic_state": "LOW",
    "severity": "LOW",
    "confidence": 0.91
  },
  {
    "frame_index": 498,
    "timestamp_sec": 16.62,
    "total_vehicles": 6,
    "cars": 2,
    "bikes": 3,
    "buses": 0,
    "trucks": 1,
    "density_score": 30.0,
    "traffic_state": "LOW",
    "severity": "LOW",
    "confidence": 0.91
  },
  {
    "frame_index": 501,
    "timestamp_sec": 16.72,
    "total_vehicles": 5,
    "cars": 2,
    "bikes": 2,
    "buses": 0,
    "trucks": 1,
    "density_score": 25.0,
    "traffic_state": "LOW",
    "severity": "LOW",
    "confidence": 0.91
  },
  {
    "frame_index": 504,
    "timestamp_sec": 16.82,
    "total_vehicles": 8,
    "cars": 3,
    "bikes": 4,
    "buses": 0,
    "trucks": 1,
    "density_score": 40.0,
    "traffic_state": "LOW",
    "severity": "LOW",
    "confidence": 0.91
  },
  {
    "frame_index": 507,
    "timestamp_sec": 16.92,
    "total_vehicles": 5,
    "cars": 2,
    "bikes": 2,
    "buses": 0,
    "trucks": 1,
    "density_score": 25.0,
    "traffic_state": "LOW",
    "severity": "LOW",
    "confidence": 0.91
  },
  {
    "frame_index": 510,
    "timestamp_sec": 17.02,
    "total_vehicles": 3,
    "cars": 1,
    "bikes": 1,
    "buses": 0,
    "trucks": 1,
    "density_score": 15.0,
    "traffic_state": "LOW",
    "severity": "LOW",
    "confidence": 0.91
  },
  {
    "frame_index": 513,
    "timestamp_sec": 17.12,
    "total_vehicles": 5,
    "cars": 2,
    "bikes": 2,
    "buses": 0,
    "trucks": 1,
    "density_score": 25.0,
    "traffic_state": "LOW",
    "severity": "LOW",
    "confidence": 0.91
  },
  {
    "frame_index": 516,
    "timestamp_sec": 17.22,
    "total_vehicles": 6,
    "cars": 3,
    "bikes": 3,
    "buses": 0,
    "trucks": 0,
    "density_score": 30.0,
    "traffic_state": "LOW",
    "severity": "LOW",
    "confidence": 0.91
  },
  {
    "frame_index": 519,
    "timestamp_sec": 17.32,
    "total_vehicles": 12,
    "cars": 7,
    "bikes": 4,
    "buses": 0,
    "trucks": 1,
    "density_score": 60.0,
    "traffic_state": "MEDIUM",
    "severity": "MEDIUM",
    "confidence": 0.91
  },
  {
    "frame_index": 522,
    "timestamp_sec": 17.42,
    "total_vehicles": 3,
    "cars": 1,
    "bikes": 1,
    "buses": 0,
    "trucks": 1,
    "density_score": 15.0,
    "traffic_state": "LOW",
    "severity": "LOW",
    "confidence": 0.91
  },
  {
    "frame_index": 525,
    "timestamp_sec": 17.52,
    "total_vehicles": 4,
    "cars": 2,
    "bikes": 1,
    "buses": 0,
    "trucks": 1,
    "density_score": 20.0,
    "traffic_state": "LOW",
    "severity": "LOW",
    "confidence": 0.91
  },
  {
    "frame_index": 528,
    "timestamp_sec": 17.62,
    "total_vehicles": 5,
    "cars": 3,
    "bikes": 1,
    "buses": 0,
    "trucks": 1,
    "density_score": 25.0,
    "traffic_state": "LOW",
    "severity": "LOW",
    "confidence": 0.91
  },
  {
    "frame_index": 531,
    "timestamp_sec": 17.72,
    "total_vehicles": 9,
    "cars": 5,
    "bikes": 2,
    "buses": 0,
    "trucks": 2,
    "density_score": 45.0,
    "traffic_state": "MEDIUM",
    "severity": "MEDIUM",
    "confidence": 0.91
  },
  {
    "frame_index": 534,
    "timestamp_sec": 17.82,
    "total_vehicles": 9,
    "cars": 4,
    "bikes": 2,
    "buses": 0,
    "trucks": 3,
    "density_score": 45.0,
    "traffic_state": "MEDIUM",
    "severity": "MEDIUM",
    "confidence": 0.91
  },
  {
    "frame_index": 537,
    "timestamp_sec": 17.92,
    "total_vehicles": 9,
    "cars": 5,
    "bikes": 1,
    "buses": 0,
    "trucks": 3,
    "density_score": 45.0,
    "traffic_state": "MEDIUM",
    "severity": "MEDIUM",
    "confidence": 0.91
  },
  {
    "frame_index": 540,
    "timestamp_sec": 18.02,
    "total_vehicles": 9,
    "cars": 6,
    "bikes": 2,
    "buses": 0,
    "trucks": 1,
    "density_score": 45.0,
    "traffic_state": "MEDIUM",
    "severity": "MEDIUM",
    "confidence": 0.91
  },
  {
    "frame_index": 543,
    "timestamp_sec": 18.12,
    "total_vehicles": 10,
    "cars": 7,
    "bikes": 2,
    "buses": 0,
    "trucks": 1,
    "density_score": 50.0,
    "traffic_state": "MEDIUM",
    "severity": "MEDIUM",
    "confidence": 0.91
  },
  {
    "frame_index": 546,
    "timestamp_sec": 18.22,
    "total_vehicles": 10,
    "cars": 4,
    "bikes": 3,
    "buses": 0,
    "trucks": 3,
    "density_score": 50.0,
    "traffic_state": "MEDIUM",
    "severity": "MEDIUM",
    "confidence": 0.91
  },
  {
    "frame_index": 549,
    "timestamp_sec": 18.32,
    "total_vehicles": 10,
    "cars": 3,
    "bikes": 4,
    "buses": 0,
    "trucks": 3,
    "density_score": 50.0,
    "traffic_state": "MEDIUM",
    "severity": "MEDIUM",
    "confidence": 0.91
  }
];
